== Chapter I. On Conversion, and Regeneration.

When our Lord Jesus Christ was transfigured on the mount,
the voice from the excellent glory bore witness of him, saying, "`This is my beloved Son,
in whom I am well pleased; Hear Him,`" (2 Pet. 1:17, Matt. 17:5) --He,
whose doctrine we are thus commanded to hear, and of course reverently to embrace,
declared, (John 3:16) "`God so loved the world, that he gave his only begotten Son,
that whosoever believes in him, should not perish, but have everlasting life.
(17th) For God sent not his Son into the world, to condemn the world; but that the world,
through him, might be saved.
(18th) He that believes on him, is not condemned: but he that believes not,
is condemned already;
because he has not believed in the name of the only begotten Son of God.
(19th) And this is the condemnation, that light is come into the world,
and men loved darkness rather than light, because their deeds were evil.
(20th) For every one that does evil hates the light, and does not come to the light,
lest his deeds should be reproved.
(21st) But he that does the truth, comes to the light,
that his deeds may be made manifest, that they are wrought in God.`"^
footnote:[In the 16th verse of the above quotation,
faith in the Son of God is set forth as necessary to the obtaining everlasting life.
In the 18th verse, condemnation is represented as the result of unbelief in his name.
In the 19th and 20th verses, the cause of condemnation is more particularly described,
being declared to consist in the not loving, but hating,
which of course includes the not believing in, the light.
Hence it appears, that in this very important passage of Scripture,
the light should be regarded as the spiritual
manifestation of the Son of God in the soul of man;
"`I, (said Christ) am the light of the world.`"
(John 8:12) The light may also be considered as one of the divine attributes,
which are comprised in the name of the Son of God.
In taking this view of the subject,
there is no essential discordance in the several parts
of this portion of the doctrine of our holy Redeemer,
respecting the object of faith: Christ, the ever blessed Son of God,
is the object of saving faith; and this faith,
when first brought forth in the newly awakened soul, is very small,
even comparable to "`a grain of mustard-seed;`" yet it
is sufficient to enable the humble recipients,
to believe in Christ revealed in their souls, under the manifestation of "`the light.`"
Through "`the obedience of faith,`" they witness its gradual increase,
and they become capable of believing in Christ,
in respect of all his other gracious offices as set forth in the holy Scriptures,
if they have access to that sacred record.
The believing in "`the light`" is expressly enjoined by our Savior in the text.
(John 12:36)]

By this highly important declaration of our holy Redeemer, it appears,
that the salvation of God through him,
is not limited to any particular class or portion of mankind; for God so loved the world,
that he gave his only begotten Son, "`that the world, through him, might be saved.`"
The Son of God "`tasted death for every man;`" (Heb. 2:9) and his salvation is
partaken of by every one who truly and availingly believes in his name.
Now the name of the Son of God, in this and in many other places of the New Testament,
appears to signify, or have reference to, his divine attributes, namely his power, life,
light, etc.;^
footnote:[See Cruden`'s Concordance under "`Name,`" also Barclay`'s Apology,
Tuke`'s Principles, Bates`' Doctrines; the three last under the article "`Baptism.`"]
and this light being "`the life`" of "`the Word,`" or Son of God, is that "`true light,
which enlightens every man that comes into the world.`" (John 1:4-9)

By this light, shining in the hearts of all the children of men, they are, at seasons,
reproved and convicted of sin; "`for all have sinned,
and come short of the glory of God.`"
(Rom. 3:23) They who do not reject this light,
are enabled to see the miserable state they are in while unregenerate,
being in bondage under the power of sin, and defiled by its pollution.
Deeply humbled by this view of their own real condition, their hearts are contrited,
--they are brought to repentance;--and the cry is raised,
"`God be merciful to me a sinner.`"
(Luke 18:13) Abiding in patient submission, under the operation of the divine power,
they are prepared for the reception of an
increased manifestation of the light of the Word,
or Spirit of Christ, whereby faith, (which is its fruit,
and which in some degree had been previously exercised,) is now more fully confirmed.
Thus the work of conversion advances in those
who do not reject the appearance of the light,
which is the free gift or "`grace`" of God.
(Titus 2:11) By the operation of his power,
the eyes of the mentally blind are in degree opened,
and some true sensibility is imparted to their souls.
They are brought to feel more deeply, the inestimable value of a Savior; and,
coming to him in faith, through the attraction of the love of God,^
footnote:["`No man can come unto me, except the Father, which has sent me, draw him.`"
(John 6:44)]
they are favored to experience the baptism of his Spirit;
witnessing the remission of their past sins through His blood,
who is "`the propitiation for the sins of the whole world.`"
(1 John 2:2) They who thus walk in the light of Christ,
in "`the obedience of faith,`" are enabled, like the believers formerly,
"`to rejoice in God, through our Lord Jesus Christ;`" by whom they receive
"`the atonement,`" or reconciliation with God.
(Rom. 5:11) Abiding under the baptism of the Spirit,
its cleansing operation progresses in their hearts;
the motives--the secret springs to action--are purified from the alloy of sin,
however specious the form under which it lurks.
This process, in the figurative language of Scripture, is said to be "`with fire.`"
(Luke 3:16)

The soul-satisfying peace and joy, which these have found to result from believing in,
and obeying, the light or Spirit of Christ,
engage them still to adhere to its manifestations;
they submit not only their words and actions,
but also the thoughts and desires of their hearts,
to its righteous scrutiny and decision; so that every sinful thought and desire,
every idle word, and every evil deed, are brought unto judgment.
They see, in this light, that there is much more to be effected in their hearts,
by the "`refiner`'s fire,`" (Mal. 3:2) than previously they had any conception of;
and they are made sensible, that this purifying process must be endured,
in order that the selfishness, pride and haughtiness,
with all other evil affections and lusts,
which the tempter strives to excite and foster in their hearts, may be fully subdued,
and made to give place to the righteousness, the love, the purity,
the meekness and the gentleness of Christ.
Amidst their many besetments, by watching unto prayer,
and by patiently waiting on the Lord in spirit, an increase of strength is received,
and they are enabled to hold on their way.-- Continuing to follow the light
of Christ in the path of self-denial,--taking up their daily cross,
(Luke 9:23) and not conforming themselves to the vain customs, fashions,
and maxims of this world,--nor fixing their affections
on its riches or pleasures,--but breaking off from,
and avoiding, every thing which the light discovers to be evil,
they gradually witness the advancement of the
new birth in their souls:--old things pass away,
and all things become new.
(2 Cor. 5:17) The floor of the heart, figuratively speaking, becomes cleansed;
and the chaff burnt up "`with unquenchable fire.`"
(Matt. 3:12) Having thus received Christ Jesus the Lord,
he gives them "`power to become the sons of God,
(this grace being dispensed) to them that believe on his name.`" (John 1:12)

The preceding description of the commencement, and progress of conversion,
is not put forth as an exact delineation of the steps, by which every one is conducted,
in whom this important work has been accomplished.
The degree of depravity, by which the human character is marked,
previously to conversion, is much greater in some cases, than in others.
The repugnance, also,
of the natural disposition to submit to the control and guidance of the light of Christ,
and thus to come under his yoke, varies greatly in different persons;
and consequently a corresponding variation may be requisite, in the duration,
and in the intensity, of "`the refiner`'s fire.`"
And when individuals of a serious disposition have embraced doctrines which,
by leading them to place an undue stress on outward forms and ceremonies,
do really obstruct their coming to Christ, their prejudices are not easily overcome;
these have to pass through a time of stripping--of breaking to pieces all those things,
however highly esteemed,
the tendency of which is to prevent their receiving Christ in
the simplicity and humility of little children.
(Matt. 18:3) It may be expected, therefore, under this great diversity of character,
that in the process of conversion,
there would be "`diversities of operations:--but it is the same God,
which works all in all.`" (1 Cor. 12:6)

The foregoing view of faith in the name of the Son of God appears to have been set
forth by Him in the latter part of that memorable portion of Scripture,
with which this chapter commences.
When our holy Redeemer had declared, "`He that believes not, is condemned already;
because he has not believed in the name of the only
begotten Son of God;`" (John 3:18) he proceeded,
as already observed, still more particularly to point out the cause of condemnation:
for he immediately added, "`And this is the condemnation,
that light is come into the world, and men loved darkness rather than light,
because their deeds were evil.
For every one that does evil hates the light, and does not come to the light,
lest his deeds should be reproved.
But he that does the truth, comes to the light, that his deeds may be made manifest,
that they are wrought in God.`"
From these words of our blessed Savior, it may be inferred,
that although professed Christians may be very assiduous in acquiring the
literal knowledge of the doctrines contained in the Holy Scriptures,
and may profess an unlimited confidence in the benefits resulting
from the sufferings and death of our Lord Jesus Christ;
yet if they persist in disregarding and rejecting the admonitions of the light,
which at seasons shines in their hearts,
in order to their being delivered from the power of sin, and cleansed from its pollution;
they do not, according to his doctrine, truly believe in his name,
and consequently they are in a state of condemnation.
For such persons to conclude,
while they remain in this state of unbelief and disobedience,
that because they profess a faith in the personal appearance, sufferings,
and death of Christ, therefore they are cleansed from their sins in his blood,
and are justified in his sight, would be indeed a lamentable and dangerous delusion.

In the texts before quoted from the sacred record, the Savior of the world briefly,
yet in clear and emphatic language, preached the doctrine of the light; showing,
that this divine gift is embraced and adhered to,
by every one who "`does`" or walks in the path of
"`truth;`" and that it is hated by all who do evil;
who reject it, in order to escape from its convictions.
Now, these two classes comprehend all mankind; and therefore it is clear,
that this divine gift is dispensed unto all.
Evil men could not hate or reject the light,
if it did not in some degree illuminate their minds,
reproving them on account of their evil deeds.
Their not believing in, nor loving the light--refusing to hearken unto,
and to obey its admonitions--gratifying their corrupt propensities by
continuing in their evil ways,--this is the ground of their
condemnation--the cause of their exclusion from that salvation,
which is by and through Jesus Christ.
On the other hand, they who walk in the paths of "`truth`" and righteousness,
in the obedience of faith, following the guidance of the light,
ordering their conduct and conversation according to its
dictates,--all who take this course and persevere therein,
are brought out from the darkness and death of our fallen nature,
and are made partakers of the salvation of God, through Jesus Christ their Redeemer.
(See 1 John 1:7)

But although all mankind may be comprised in these two classes,
yet it is a truth clearly deducible from the doctrines of Scripture,
that individuals may pass from either of these classes into the other.
Those who have begun to walk in the paths of truth and righteousness,
and even such as have made considerable advancement in a religious life, may,
by not abiding in the fear of God, and in obedience to his holy will,
fall into temptation, and be overcome thereby, and thus become evil doers.
(Ezek. 33:18, 1 Cor. 9:27) So also, if individuals of the latter description,
before the day of mercy passes away,
happily embrace the renewed visitations of a long-suffering and gracious God,
they may undoubtedly, through sincere repentance and faith in his Son Jesus Christ,
be cleansed from the pollution of sin,
and be brought into a state of reconciliation and favor with God.
Thus the declaration of the Apostle to the Corinthians will be applicable to them;
when describing various kinds of evil doers, he adds, "`And such were some of you;
but you were washed, but you were sanctified,
but you were justified in the name of the Lord Jesus, and by the Spirit of our God.`"
(1 Cor. 6:11)

Among other declarations of Christ, in accordance with the foregoing, are these:
"`I am the Light of the world; he that follows me, shall not walk in darkness,
but shall have the light of life.`"
(John 8:12) To some of the Jews who, through unbelief,
were in danger of having this divine gift taken from them, he said,
"`Walk while you have the light, lest darkness come upon you.`"
"`While you have light, believe in the light, that you may be the children of light.`"
(John 7:35-36) These declarations of Christ,
in which he represents himself under the character of
"`the Light,`" appear to have reference to him,
principally as that divine Word, the life of which, as the Apostle declares,
is "`the light of men.`"
(John 1:4) By the operation of this Word,
the work of regeneration is effected in them who believe, and walk in its light.
They are "`born again, not of corruptible seed, but of incorruptible,
by the Word of God which lives and abides forever.`"
(1 Peter 1:23) Thus they become children of light--in other words, true Christians.

It may further be observed, that all who believe in the light of Christ,
and walk in obedience to its manifestations from day to day,
fully participate in the benefits procured by the sufferings and death of the Redeemer.
"`If we walk in the light`" said the Apostle, "`as he is in the light,
we have fellowship one with another,
and the blood of Jesus Christ his Son cleanses us from all sin.`"
(1 John 1:7) Hence it appears that the being cleansed from all sin,
by the blood of Christ, is the blessed privilege of those who walk in the light.

Christ is the gift of God unto mankind, not only in respect of his outward,
or personal appearance, sufferings, and death,
but also in respect of his spiritual manifestation in their hearts.
The Almighty declares, "`I will give you for a light to the Gentiles,
that you may be my salvation to the end of the earth.`"
(Isa. 49:6) His salvation is freely offered unto all;
but it is partaken of by those only,
who in humility of mind receive and obey this manifestation of his holy light, or Spirit;
and embracing the faith, which is its fruit,
are baptized in or into the name--the life and power, of the Father, Son,
and Holy Spirit:--as it is written, "`He that believes and is baptized, shall be saved.`"
(Mark 16:16) The faith of these will necessarily
embrace the testimony of the Holy Scriptures,
if they have access to this invaluable record respecting the birth, life, doctrine,
miracles, death, resurrection, and ascension of our Holy Redeemer;
for the gift of the light, or Spirit of Christ,
(especially with respect to the increased measure,
in which it is granted under the Christian dispensation,) is
altogether to be ascribed to the efficacy of that which Christ,
in his appearance in the flesh, did and suffered for the human race.
Thus the benefits of the "`one offering,`" are not depreciated,
but are more completely exalted by the doctrine of the manifestation of the Spirit,
or universal saving light and grace.

It is evidently the practice of the wicked one, to endeavour, by various stratagems,
to induce the children of men to shut up their hearts against the influence of the light,
or Spirit of Christ; and as far as he succeeds in this design,
so far he maintains his evil power and dominion in the world.
If, for instance, the subtle adversary, in order to effect his purpose,
can so far beguile any of the professors of Christianity, as to instill into their minds,
a secret aversion to the heart-searching manifestation of the light of Christ; and if,
by following up the advantage he has gained,
he can induce them to affix on this doctrine, the stigma of enthusiasm, or fanaticism,
it then becomes easy for him to persuade them to disregard and to reject altogether,
the admonitory dictates of this divine teacher in their own minds,
in order that he may without restraint bring
forth his own works of darkness in their hearts.
But He who was manifested "`to take away our sins,`" was also
"`manifested to destroy`" these "`works of the devil.`"
When this blessed light of Christ is believed in,
and allowed freely to shine in our hearts, the works of the adversary,
at their very origin, are clearly detected;
and if its warnings and requisitions are embraced, we are enabled,
through the power which it imparts,
to "`overcome the wicked one`" in his various devices,--
"`to deny ungodliness and worldly lusts,
and to live soberly, righteously, and godly, in this present world.`" (Titus 2:11-12)

The great importance of this divine gift unto mankind, appears very evident,
in the account given of it by our Lord Jesus Christ,
in the texts which have been already quoted.
The apostolic epistles also, furnish corroborating testimony,
by the designations under which they describe it,
and by the effects which they attribute to it. In the Epistle to the Corinthians,
it is declared, that "`God, who commanded the light to shine out of darkness,
has shined in our hearts, to give the light of the knowledge of the glory of God,
in the face (or manifestation) of Jesus Christ.
But we have this treasure in earthen vessels,
that the excellency of the power may be of God,
and not of us.`" (2 Cor. 4:6-7) The same Apostle describes this divine gift also,
as "`The grace of God, that brings salvation, and has appeared unto all men.`"
(Titus 2:11-12) He also represents it as "`the Spirit of God`" or "`of Christ.`"
(Romans 8:9) "`A manifestation whereof, is given to every man to profit with.`"
(1 Cor. 12:7) It is also called "`the Anointing,`" which "`teaches of all things.`"
(1 John 2:27) "`Christ in you the hope of glory.`"
(Col. 1:27) The 5th verse in the 13th chapter of 2 Corinthians is very emphatic:
"`Examine yourselves whether you are in the faith, prove your own selves;
do you not know yourselves, that Jesus Christ is in you, unless indeed you are reprobates.`"^
footnote:["`Reprobates,`" that is, not approved.]
"`All things that are reproved, are made manifest by the light, etc.`" (Eph. 5:13)

In addition to the above, the following texts are adduced,
as having reference to the same divine gift,
under the character of  "`the Word,`" or "`the Word of God.`"
There are some professing Christians, however,
who suppose that these texts should be understood as referring to the Scriptures;
the impropriety of this supposition, it is apprehended will be evident,
if a portion of the context, which will now be quoted, be duly considered.
It will be found to embrace attributes, which, it is conceived, are ascribable,
not to the Scriptures, but to Christ, who is "`the Word,`" by whom the world,
and all things in it, were created.
(Heb. 11:3) The Apostle Paul declares, that the righteousness which is of faith,
speaks in this way, "`Say not in your heart, Who shall ascend into heaven? (that is,
to bring down Christ from above:) or, Who shall descend into the deep? (that is,
to bring up Christ again from the dead.) But what does it say? The word is near you,
even in your mouth, and in your heart: that is, the word of faith, which we preach.`"
(Rom. 10:8) The Apostle James exhorts, "`Receive with meekness the engrafted word,
which is able to save your souls.`"
(James 1:21) The Apostle Peter addresses the believers as "`being born again,
not of corruptible seed, but of incorruptible, by the Word of God,
which lives and abides forever.`"
"`All flesh is as grass,`" etc, but "`the Word of the Lord endures forever.`"
(1 Peter 1:23-25) In the Epistle to the Hebrews,
we have a very particular description of this divine Word.
The apostle declares, that "`the Word of God is quick, and powerful,
and sharper than any two-edged sword,
piercing even to the dividing asunder of soul and spirit, and of the joints and marrow,
and is a discerner of the thoughts, and intents of the heart.
Neither is there any creature that is not manifest in his sight;
but all things are naked, and opened unto the eyes of him,
with whom we have to do.`" (Heb. 4:12-13) Here this eminent Apostle
ascribes the divine attribute of omniscience to the Word of God.
Now they who say the "`Word of God,`" described in this text, is the Scriptures,
must of course ascribe this attribute (omniscience) to them; but in doing this,
they should consider whether they are not subjecting themselves to
the serious imputation of idolizing the Scriptures.

The Apostle Paul teaches us, that the Holy Scriptures were given by divine inspiration;
and are "`profitable for doctrine, for reproof, for correction,
for instruction in righteousness, that the man of God may be perfect,
thoroughly furnished unto all good works;`" and
they "`are able to make wise unto salvation,
through faith, which is in Christ Jesus.`"
(2 Tim. 3:15-17) They bear testimony to Christ, as the Savior of the world;
setting forth the doctrine which he preached, when personally on earth,
and describing what he did and suffered for mankind.
They also hold forth very clear declarations respecting
his spiritual appearance in their souls,
in order to effect their regeneration and sanctification.
But in the various dispensations of "`his grace and truth`" unto mankind,
the Lord Jesus Christ "`the High Priest of our
profession,`" (Heb. 3:1) works immediately,
or by outward means, as he pleases.
Indeed, one of the distinguishing excellencies of the Christian dispensation is,
that it leads to a communion with the Father and the Son,
which is not dependent on any external medium.
Through Christ we have "`access by one Spirit unto the Father.`"
(Eph. 2:18) While we highly esteem the benefit to be derived from the sacred record,
we should not forget, that we shall abuse this precious gift, if we exalt it,
so as to put it in the place of Him, who is thus described:
"`In the beginning was the Word, and the Word was with God,
and the Word was God.--All things were made by Him.--In Him was life,
and the life was the light of men.`"
(John 1:1,3,4) Let us then,
in ascribing to the Bible all the honor which
the inspired writers themselves attribute to it,
be careful not to exalt it above, nor to place it on an equality with,
Christ or the Holy Spirit, from whom its authority is derived.^
footnote:[Such however is the deference that is due to this authority,
that the Scriptures are to be considered as the only fit outward test,
by which controversies among Christians on religious subjects are to be decided;
so that whatsoever doctrine is contrary to their testimony,
may therefore justly be rejected as false; and whatsoever any persons,
pretending to the Spirit, may do, which is contrary to the Scriptures,
should be considered as the effect of delusion.
See R. Barclay`'s Apology, Prop. 3.]

[.asterism]
'''

In publishing this concise view of the commencement and
progress of vital religion in the soul,
the writer wishes to observe,
that probably it may fall into the hands of religiously
disposed persons of different denominations;
some of whom may be ready to say,
'this doctrine does not accord with that which we have
been accustomed to hear from our ministers;
it is a doctrine, which, in many material points, as far as our observation has extended,
is seldom heard from the pulpit in the present day.`' Should
objections of this kind be excited in the minds of any persons,
who in sincerity of heart are seeking that knowledge which "`is life
eternal;`" (John 17:3) the writer entreats them to consider,
that this doctrine was promulgated by our Lord Jesus Christ himself;
and that his Apostles preached substantially the same truths; of which assertion,
abundant proof may be found,
by reference to the various texts quoted in the preceding paragraphs.

While the reader is engaged in the investigation of this momentous subject,
he is also earnestly entreated to recur to his own experience,
in past seasons of serious reflection.
Have you not witnessed, at least in some degree,
the truth of the declarations of Scripture, to which, in the preceding pages,
your attention has been directed?--Has not the light of Christ shone in your
heart?--Has it not awakened you from a state of carnal security,
and placed your transgressions in order before you,--
soliciting you to break off from your sins by repentance and
amendment of life?--You may be well assured of this truth,
that it is not the work of your soul`'s enemy, thus to detect,
and to lay open his own devices: he seeks to deceive, to cover up,
and to darken his own ways and baits,
that their real nature and tendency may not be discovered.
It is the light of Christ Jesus our adorable Redeemer that detects, and makes known,
the workings of the grand deceiver.
If then you are now convinced,
by the concurrent testimony of the Light or Spirit of Christ, and of Holy Scripture,
that the doctrine preached by men,
(whom you have esteemed as ministers of the gospel) is
not in full accordance with that which Jesus Christ,
and his Apostles, preached;
surely eternal happiness is involved in your faithfully embracing the latter.
And should this course of inward conviction and renovation of heart,
prove very contrary to your natural inclination,
so as to be indeed a cross difficult to be endured; yet, remember who it is that said,
"`Whosoever does not bear his cross, and come after me, cannot be my disciple.`"
(Luke 14:27) Be encouraged, then, to bear this cross, and faithfully to follow Christ,
in the path of self-denial.
It is one of the greatest privileges held out to you, by the Christian dispensation,
that He is given to be your "`Leader`" your spiritual Guide: (Isa. 55:4) and if,
in humility of mind, you obey the monitions of his holy light revealed in your heart,
you herein follow Christ.

As this is an important point of Christian doctrine,
the writer is inclined to repeat the assertion, that he, who truly believes in,
and follows the light of Christ, is really a believer in, and follower of Christ;
and therefore, a partaker of the benefits resulting from his sufferings and death.^
footnote:[This assertion is not invalidated by the fact,
that some persons who have professed (although falsely)
a belief in the Light or Spirit of Christ,
have disregarded and rejected the Holy Scriptures.
As the sacred Record was written under the inspiration of the Holy Spirit,
and as this divine Teacher, in itself, is unchangeable,
it evidently follows that its influence never can lead anyone
to contemn that which it has dictated for our instruction.
Therefore they who disregard and reject the Holy Scriptures, do plainly show,
whatever they may profess, that their minds,
instead of being under the influence of the Light, or Spirit of Christ,
are involved in gross darkness and delusion.]
On the contrary, he who practically disregards and rejects this Light,
disregards and rejects Christ; and thus deprives himself of that salvation,
which those who believe in and follow Christ, partake of.
These positions are supported by the texts quoted in the beginning of this chapter,
taken in connection with John 8:12,
and 1 John 1:7. Corroborating testimony appears also,
in the following gracious declaration of the Almighty concerning Christ, already quoted:
"`I will give you for a light to the Gentiles^
footnote:[The word "`Gentiles,`" in the language of Scripture,
appears to signify all mankind excepting the Jews.]
that you may be my salvation to the ends of the
earth`" (Isa. 49:6) They who believe in,
and follow this divine Light,
are favored with access to the fountain of wisdom and strength.
Through faith they receive power to fulfill its requisitions;
and the obedient are rewarded with peace and joy.
"`Thanks be unto God for his unspeakable gift!`"

May the attention of the sincere seekers after truth be turned, day by day,
to this inward monitor, the true spiritual Guide.
It will not lead you in the least degree to disregard the Holy Scriptures;
on the contrary,
it will enable you to understand them more truly in the sense in which they were written,
than the best unassisted faculties of man can do;
and to apply them most effectually to your individual instruction and comfort: moreover,
the harmony which you will witness, as you advance in your religious progress,
between the law of the Spirit written on the heart,
and the precepts and doctrines contained in the Bible,
as far as the latter apply to your individual states respectively,
will not fail to afford you much satisfaction and encouragement.
That you may then be kept from falling into any temptation,
by which the enemy may strive to mar the Lord`'s work in your souls,
may your secret aspirations, under the influence of the Spirit of Christ,
frequently ascend unto your heavenly Father, with fervent desires,
that his kingdom may come, and be set up in your hearts,
and that his holy will may be done, in and by you, even in all things;
and when the Light of Christ points out what he requires of you, as individuals,
both in doing that which is right in his sight, and in avoiding that which is evil,
may the language of each soul be,--"`Not my will, O Lord, but yours be done!`"
By thus endeavoring, in all things, to follow your Redeemer, through that divine aid,
which will assuredly be granted unto every one, who seeks it in sincerity of heart;
his gracious declaration, already quoted,
will be fulfilled in your experience;--"`I am the light of the world; he that follows me,
shall not walk in darkness, but shall have the light of life.`"

The Apostle Paul made this observation respecting the
Jews:--"`When Moses is read,`" (who wrote of Christ,
John 1:45) "`the veil is upon their heart; nevertheless when it shall turn to the Lord,
the veil shall be taken away.`"
(2 Cor. 3:15-16) So also it may be said now,
of very many professed Christians,--that when they read the New Testament, the veil is,
in some measure, upon their heart:
for although they receive the doctrine held forth in the Scriptures,
concerning the outward, or personal appearance of Christ,
his sufferings and death for mankind, which doctrine the Christian faith fully embraces;
yet they are deficient in respect of that important article of the same faith,
which the Apostle enforces in this emphatic language,--"`Examine yourselves,
whether you are in the faith; prove your own selves.
Do you not know yourselves,
that Jesus Christ is in you--unless indeed you are
reprobates?`" (2 Cor. 13:5) He also declares that,
"`If any man have not the Spirit of Christ, he is none of his.`"
(Rom. 8:9) We may, however, confidently entertain the same assurance,
concerning the professed Christians now adverted to,
as the Apostle expressed respecting the Jews; that is,
that when their heart "`shall turn to the Lord, the veil shall be taken away.`"
When this change takes place,
(O that it may be speedily effected!)--they will then be prepared to receive the Light,
or Spirit of Christ,
for their "`Leader;`" (Isa. 55:4) and by submitting to his heart-purifying baptism,
and following him in the path of regeneration and sanctification,
they will bring forth the fruit of the Spirit, through its quickening,
life-giving influence.
This fruit, the Apostle declares, is "`Love, joy, peace, long-suffering, gentleness,
goodness, faith, meekness, temperance.`"
(Gal. 5:22-23) Again, "`The fruit of the Spirit is in all goodness,
and righteousness, and truth.`"
(Eph. 5:9) What greater blessing can the most enlightened
philanthropist desire for the whole human race,
than this,--that the fruit of the Spirit, as above described,
may be universally brought forth? Moral evil
would then be driven from the face of the earth;
"`The kingdoms of this world [would]
become the kingdoms of our Lord, and of his Christ; [who]
shall reign forever and ever.`" (Rev. 11:15)
