== Concluding Observations.

In reviewing the subjects adverted to in these pages,
the writer is inclined to say a little more on some of them,
especially on that very important one,
the benefits resulting to mankind from the sufferings and
death of our blessed Savior Jesus Christ on the cross:
this is followed by some additional remarks respecting worship and ministry,
with an exhortation to professed Christians.

The Scriptures declare, that the "`Word which was in the beginning with God, and was God,
was made (or took) flesh.`"
(John 1:1-14) "`As the children are partakers of flesh and blood,
he also himself likewise took part of the same;
that through death he might destroy him who had the power of death, that is the devil.`"
(Heb. 2:14) "`He is the propitiation for our sins, and not for ours only,
but also for the sins of the whole world.`"
(1 John 2:2) He suffered death on the cross, and was buried.
On the third day he rose from the dead and ascended into heaven, where,
glorified with the Father, he is our Mediator and Intercessor with him.

In proceeding to describe more particularly the benefits which
result to mankind from the death of Christ,
the sentiments of the writer on this subject being well
expressed in R. Barclay's "`Apology for the true Christian
Divinity,`" he inserts the following selection from that work.

[quote, , "Apology, prop. 7, sec.3"]
____
We consider our redemption in a twofold respect or state; both which,
in their own nature are perfect; though in their application to us, the one is not,
nor can be, without respect to the other.

The first is, the redemption performed and accomplished by Christ for us,
in his crucified body, without us: the other is the redemption wrought by Christ in us;
which no less properly is called and accounted a redemption than the former.
The first, then, is that whereby a man, as he stands in the fall,
is put into a capacity of salvation; and hath conveyed unto him a measure of that power,
virtue, spirit, life, and grace, that was in Christ Jesus; which,
as the free gift of God, is able to counterbalance, overcome, and root out the evil seed,
wherewith we are naturally, as in the fall, leavened.--The second is that,
whereby we witness and know this pure and perfect redemption in ourselves, purifying,
cleansing, and redeeming us from the power of corruption; and bringing us into unity,
favor, and friendship with God.

By the first of these two, we that were lost in Adam,
plunged into the bitter and corrupt seed, unable of ourselves to do any good thing,
but naturally joined and united to evil; forward and propense to all iniquity,
servants and slaves to the power and spirit of darkness, are, notwithstanding all this,
so far reconciled to God, by the death of his Son, while enemies,
that we are put into a capacity of salvation,
having the glad tidings of the gospel of peace offered unto us;
and God is reconciled unto us in Christ, calls and invites us to himself.
In which respect we understand these Scriptures: 'He slew the enmity in himself.
He loved us first.--He who did no sin,
his own self bare our sins in his own body on the tree.
And he died for our sins, the just for the unjust.'
(Eph. 2:15; 1 John 4:10; 1 Peter 2:22,24, and 3:18)

By the second, we witness this capacity brought into act; whereby receiving,
and not resisting, the purchase of his death, to wit, the light, Spirit,
and grace of Christ revealed in us, we witness and possess a real,
true and inward redemption from the power and prevalency of sin;
and so come to be truly and really redeemed, justified, and made righteous,
and to a sensible union and friendship with God.
Thus, 'he gave himself for us, that he might redeem us from all iniquity;' and thus,
'we know him, and the power of his resurrection, and the fellowship of his sufferings,
being made conformable to his death.' (Tit. 2:14;
Phil. 3:10) This last follows the first in order, and is a consequence of it,
proceeding from it as an effect from its cause;
for as none could have enjoyed the last without the first had been (such
being the will of God,) so also can none now partake of the first,
but as he witnesseth the last.
Wherefore as to us, they are both causes of our justification;
the first the procuring efficient, the other the formal cause.
____


As it is evident from Scripture testimony,
that it is absolutely requisite to our complete redemption,
that we should individually believe in the divine light or Spirit of Christ,
and by submission to his baptism, witness the work of regeneration in our souls,
how desirable is it, that among all professed Christians,
(as hath been already hinted,) no doctrines should be embraced,
nor any ordinance or institution relative to ministry and worship set up, and practised,
the tendency of which is, to divert their attention from this internal teacher,
or in any degree to obstruct or restrain its influence and operation in the soul.
An attentive perusal of the New Testament, will show,
that one of the principal objects of the ministry of Jesus Christ,
and also of his Apostles, was, to turn the attention of the people to this divine gift,
as their teacher and guide, in the way to everlasting happiness.
And surely this should be a principal object,
in the view of every professed minister of Christ in the present day;
for the Christian religion is, in itself, the same now as it was in the apostolic age;
yet, alas! great is the degeneracy from its original purity,
among many of its professors, not only in regard to conduct and conversation,
but also respecting doctrine and worship.

True believers in Christ, after their conversion,
and the remission of their past sins through his blood,
are still liable in their intercourse with the world,
when the daily watching unto prayer is not fully maintained,
to contract contamination from its spirit, and also from the flesh and the devil;
which contamination when received, however minute it may be,
cannot escape the detection of Him who seeth all things.
In the degree in which this has prevailed,
it tends to obstruct the access of the soul unto God,
who is a Being of infinite purity and holiness.
Now the great Head of the church, the High-priest and Bishop of souls,
beholds the state of every individual in religious assemblies, and does not fail,
when he sees meet, to dispense unto every one according to his need,
who in the exercise of faith and love comes to him.
He breaks the bread of life unto the pure in heart,
and in his abundant mercy he gives repentance and contrition of soul unto those, who,
through unwatchfulness have contracted any degree of defilement,
"`sprinkling their hearts from an evil conscience.`"
(Heb. 10:22) thus the gracious declaration of our Lord is verified,
"`Where two or three are gathered together in My name,
(and consequently when a larger number is so gathered,) there
am I in the midst of them;`" (Matt. 18:20) for these words
of our holy Redeemer are not unmeaning sounds:
they are definite and most certain truths.
What a blessed privilege then is it,
that a religious assembly may witness the life-giving
presence of Christ revealed in and among them!
But it should ever be borne in mind, that this high privilege is held out to those,
and to those only, who are gathered in his name; which, as already observed,
signifies or has reference to his divine attributes, viz.
his power, life, light, etc.
That we may participate in this high privilege,
the command of our Holy Redeemer to his disciples, "`What I say unto you I say unto all,
Watch!`" and again, "`Watch and pray, that ye enter not into temptation,`" (Mark 13:37;
Matt. 26:41) should never be forgotten:
it is indeed a duty very needful to be observed in the
course of our daily conduct and conversation among men;
but on no occasion is the practice of it more necessary,
than in assemblies for public worship.
For there is ground to believe, that the enemy of all good, strives,
by every means in his power,
to prevent the worshipping of Almighty God in spirit and in truth;
and the human mind by its own strength is entirely incompetent to withstand his efforts.
As, therefore, the declaration of Jesus Christ on this important subject,
"`The hour cometh, and now is,
when the true worshippers shall worship the Father in spirit and in truth;
for the Father seeketh such to worship him,`" (John 4:
23) affords sufficient ground for the conclusion,
that it is consistent with the will of our heavenly Father that this
pure spiritual worship should everywhere prevail,--how indispensable
to the being preserved from opposition to the divine will,
in this particular, when assembled for the purpose of divine worship, is a uniform,
implicit adherence to the injunction of our Lord,--even that "`all,`" of
every denomination in his militant church,
should "`watch;`" that so, under the influence of his Holy Spirit,
the supplications of their souls may ascend unto him,
that they may not enter into any of the temptations of the enemy,
including the temptation to preach, or vocally to pray or sing,
before the quickening influence of the Spirit of Christ
is felt distinctly to lead unto any one of these acts.

In the duty of watching, that of waiting upon God may be considered to be included;
and if this duty be patiently persevered in,
there is a gracious assurance that the result will be a renewal of strength.
(Isa. 40:31) Thus invigorated, true believers,
through the loving kindness and strength of the Lord,
will surmount the temptations of their souls' adversary;
and will be enabled to worship the Father of spirits,
in spirit and in truth--in solemn reverential silence;--followed,
as often as the great Head of the church shall be pleased to direct, by vocal ministry,
prayer, and praise.
And this direction, communicated by the immediate influence of his Holy Spirit, when,
and as he seeth meet to give it, in religious assemblies,
will be clearly understood by those individuals,
(if duly watchful and attentive,) whom he may be
pleased to entrust with a gift of the ministry;
and he will also furnish them with the needful supplies of that "`wisdom,
which is from above,`" for the edification of his church.
Then their dependence being placed on this wisdom, and not on their own,
the apostolic direction will be thoroughly complied with; "`If any man speak,
let him speak as the oracles of God; if any man minister,
let him do it as of the ability which God giveth;
that God in all things may be glorified through Jesus Christ.`" (1 Pet. 4:11)

In divine worship,
agreeably with various texts of Holy Scripture bearing on this subject,
the life-giving influence of the Spirit of Christ
should be regarded as the only true spring to action.
The will and wisdom of man should not be suffered to predominate, or take the lead,
but should be kept in entire subserviency.
The general tenor of those declarations and promises which the Scriptures hold forth,
relative to Christ and his Holy Spirit,
describes him as given to mankind for their Lord--their
Leader--their Guide--their Shepherd--their High Priest, etc.
(John 13:13; Isa. 4:4; John 10:14, and 16:13; Heb. 2:17)
Now these characters convey the idea of
precedence-- of direction--of going before--but,
not of following.
Accordingly we find that when our Lord described
himself as "`the good Shepherd,`" he said,
"`When he putteth forth his own sheep, he goeth before them, and the sheep follow him;
for they know his voice.`"
(John 10:4) "`The good Shepherd`" then "`putteth
forth his own sheep`" in all their religious services,
in public assemblies, and on other occasions.
If therefore it be admitted, that the worship which is in spirit and in truth,
is performed only under the quickening influence,
and guidance of the Spirit of Christ--' it behoves the
professors of Christianity in general,
very seriously to consider, whether they are performing this worship,
when in their public assemblies they begin their religious services according to a
previously prescribed form,--and when their ministers depend on their own wisdom,
for a supply of matter for their sermons and prayers.
If, on the contrary, their worship commences in the manner,
and is performed under the circumstances now described,--or,
in respect to those professed Christians who do not use any prescribed forms of worship,
if any of their ministers be not careful reverently to wait for that "`
ability which God giveth,`" (1 Peter 4:11) and if without this essential
qualification they presume to preach or to pray in their assemblies;
it should be a subject of grave consideration,
whether in all these cases they are not proceeding
without the only sure Guide and Leader,
and substituting another leader, human wisdom, in its stead? For,
indeed we have no ground from the testimony of Holy Scripture to expect,
that the Spirit of Christ will follow us with its life-giving influence,
when in our religious assemblies we put ourselves under
the direction of our own will and wisdom,
by beginning to preach, or to pray, or to sing,
before the quickening influence of the Spirit of Christ is felt to
put forth and lead in the performance of any of these acts.

Far be it, however, from the writer,
to assign any limits to the love and mercy of our Lord Jesus Christ.
He fully believes that in very many instances,
where uprightness and sincerity of heart are found,
our Holy Redeemer graciously condescends to render religious services,
which are in some degree of the character now described,
effectual to the awakening of the unconverted,
to the convincing them of the danger of living in forgetfulness of God,
and to the exciting in their hearts a lively feeling of their want of a Savior.
How greatly is it to be desired, that this gracious condescension of infinite goodness,
may not be held up as an argument to obstruct their reception of, and obedience to,
such further manifestations of divine light,
as the great Head of the church may be pleased to dispense;
in order to enable them more clearly to discriminate
between that worship which is in spirit and in truth,
and those performances to which the appellation
of will-worship is in any degree applicable.

When it is considered that the well-being in this life,
and the eternal happiness hereafter, of every individual,
depends on his becoming not merely a nominal, but a real Christian;
the subject appears evidently one of the greatest importance: for,
as said our blessed Savior, "`What shall it profit a man if he gain the whole world,
and lose his own soul.`"
Let then every professed Christian be stimulated,
not to place his dependence on his being a member of any religious community,
or on his being in the practice of uniting in any external form of worship,
or ceremonial observance; but let him,
with an anxiety in some degree adequate to the importance of the subject,
seek an experimental knowledge of the power of God inwardly revealed;
that by submission to its humbling operation,
"`every mountain and hill (of self-exaltation,) may be brought low;`"
(Luke 3:5) that so every obstacle to his coming unto Christ,
and his partaking of the salvation which is by him, may be effectually removed.

With this important object in view,
let us apply to ourselves a portion of the doctrine adverted to in the preceding pages.
God, in his infinite love to mankind, has declared respecting Christ:
"`I will give thee for a light to the Gentiles,
that thou mayest be my salvation to the ends of the earth;
(Isa. 49:6) and our Holy Redeemer referring to this divine gift,
and describing the cause of the condemnation of those who perish,
said "`This is the condemnation, that light is come into the world,
and men loved darkness rather than light, because their deeds were evil:`" therefore,
that we may not bring on ourselves this condemnation,
by our not loving but disregarding and rejecting Christ,
under the manifestation of the Light,
let a heart-searching examination take place individually,
by our conscientious application to ourselves of the following questions:
Dost thou believe in Christ,
in reference to his spiritual appearance in thy own soul? (2 Cor. 13:5) Hast thou,
in the metaphorical language of Scripture, opened the door of the heart unto him, when,
by the secret convictions of his Holy Light or Spirit,
he has knocked there for admission? (Rev. 3:20)
Hast thou thus received Christ for thy leader,
(Isaiah 55:4) thy baptizer,
(Matt. 3:11) thy high-priest and thy king? (Heb. 2:17. Isaiah
33:22) Is it become thy daily concern to obey him in all things,
avoiding that in every part of thy conduct and conversation,
which the light manifests to be evil,
(John 3:20-21) denying thyself and taking up the cross,
in respect to every pursuit and gratification, which this divine Monitor does not allow,
however earnestly pleaded for by thy natural
inclination and desires? (Luke 9:23) And finally,
dost thou witness, through submission to the baptizing operation of his Holy Spirit,
the work of regeneration begun, and gradually progressing in thy soul? (John 3:3)

To promote this great work of reformation among
professing Christians of every denomination,
is the object which the writer has in view:
he fervently desires that the awakening visitations of divine love and mercy
may be extensively embraced,--that great may be the number of those,
who, feeling the burthen of sin, and their need of a Savior;
and under the conviction that the form of godliness without the power cannot save them;
will be prepared to accept the gracious invitation,
"`Come unto me all ye that labor and are heavy laden, and I will give you rest.
Take my yoke upon you, and learn of me, for I am meek and lowly in heart;
and ye shall find rest unto your souls.`"
As a general solicitude prevails thus to come unto Christ, to submit to his yoke,
and to learn of and to be baptized by him,
the fruit of his Holy Spirit will be abundantly produced;
genuine Christianity will again shine forth in her ancient beauty;
the name of Almighty God will be glorified by the consistent
conduct and conversation of professed Christians;
and in their religious assemblies,
the will and wisdom of man being no longer suffered to predominate,
but being kept in due subserviency, the eternal light, life,
power and wisdom of our God will be exalted in dominion over all.

'Even so, Holy Father, thy kingdom come, thy will be done on earth,
as it is done in heaven'

THE END.
