== Introduction.

When we look around us,
and observe how many conflicting creeds and systems of
religion are sedulously propagated in the present day,
our reflections on the subject should lead us to
appreciate duly the privileges with which,
through divine love and mercy, we are favored;
the Light of Christ being given to illuminate our minds,
and the Holy Scriptures being placed within our reach,
to which we can refer for instruction.
In the Sacred Record, the doctrine preached by our Lord and Savior Jesus Christ,
on the subject of the Redemption and Salvation of Man, is clearly exhibited.
As no other subject of equal interest and importance can be presented to us,
may these few pages,
designed to point out from this high authority the way by
which all mankind may come to the knowledge of the Truth,
and be saved, prove the means, under the divine blessing,
not only of convincing the merely nominal Christian of the imminent danger he is in;
but also of encouraging the weak yet sincere believer,
to hold fast the "`grain`" of living faith; (Matt. 17:20) that so,
amid all the conflicts with which he may be proved,
his confidence may be steadily fixed on Him, who is the "`Wisdom of God,
and the Power of God.`" (1 Cor. 1:24)
By submission to His command, "`Take my yoke upon you,
and learn of me;`" and, by the consequent fulfillment of his gracious promise,
"`ye shall find rest unto your souls,`" (Matt. 11:29) the sincere
believer will be enabled eventually to adopt the ancient language,
"`The Lord is my light, and my salvation;
whom shall I fear? The Lord is the strength of my life;
of whom shall I be afraid?`" (Ps. 27:1)
