[#chapter-2, short="The Worship Ordained of God"]
== Chapter II: The worship which, under the christian dispensation, is ordained of god.

In the conversation which our Lord condescended to hold with the woman of Samaria,
he declared, "`The hour cometh, and now is,
when the true worshippers shall worship the Father in spirit and in truth;
for the Father seeketh such to worship him.
God is a spirit, and they that worship him, must worship him in spirit and in truth.`"
(John 4:23-24) On other occasions he said, "`No man cometh unto the Father, but by me.`"
(John 14:6) "`Without me ye can do nothing.`"
(John 15:5) These declarations plainly indicate, that the worship of God,
under the Christian dispensation, is of a spiritual character;
and must be offered in truth;--that we cannot come unto the Father,
and offer unto him this true worship, but by Jesus Christ, who is "`the way, the truth,
and the life.`"
Now, his assistance is communicated to us by the quickening influence of His Holy Spirit,
without which the important duty of worship cannot be acceptably performed.
This appears to have been the sentiment of the Apostle Paul; for he declares,
that "`No man can say (or acknowledge) that Jesus is the Lord,
but by the Holy Ghost,`" or Spirit.
Hence it is apparent, that all worship, having a different origin,
and which is of the kind designated by the Apostle "`will-worship,`" (Col.
2:23) being merely the act of self--the mere product of the will and
wisdom of man--whether or not it be adorned with eloquence of speech,
or accompanied with vocal or instrumental music, is not the true worship of God.
Even if this worship be supported by human authority, and sanctioned by it as orthodox,
still the declaration of Jesus Christ is applicable unto it.
"`In vain they do worship me, teaching for doctrines the commandments of men.`"
(Matt. 15:9)

It may be said of merely nominal Christians in the present day, that,
although in many instances,
supineness respecting religion is the prominent feature of their character; yet,
in many other cases,
they are zealous in supporting the creeds of the religious
communities to which they are individually attached.
But they refuse to submit to the convictions of the Spirit of Christ--
they will not come to his baptism--they refuse to walk in the path of
self-denial;--and the consequence is that their hearts are not
cleansed--the chaff is not burnt up--they remain carnally-minded.
Now while they continue in this state of resistance against the Spirit of Christ,
there is cause for them to fear, that the worship which they offer to Almighty God,
is not more acceptable in his sight, than was that of the Pharisees formerly.
The Pharisees rejected Christ in his outward, or personal appearance;
the merely nominal Christians above described, reject Christ in his inward,
or spiritual appearance in their hearts.
Like the Pharisees, they think they "`have eternal life`" in the Scriptures;
and like them also, they will not come to Christ, that they "`might have life.`"
(See John 5:39-40)

But it is much to be lamented, that the adversary of mankind so much prevails,
not only in diverting the merely nominal Christian from
even entering on the true spiritual course,
but also in impeding the progress of many serious persons, who have begun to walk in it;
and who, loving the Lord Jesus in a good degree of sincerity,
have so far followed his holy guidance,
as to be redeemed from many evil customs and vanities of the world.
Yet, not patiently and humbly submitting to the operation of that power,
by which "`old things are`" made to "`pass away,`" and "`all things to become new,
and all things`" to be "`of God`" (2 Cor. 5:17-18)
their growth in the divine life is obstructed;
and their strong attachment to human prescriptions, relative to forms of worship,
and ceremonial observances,
prevents them from attaining that clearness of spiritual discernment,
into which they would have been introduced, if, in childlike simplicity,
they had been passive in the Lord`'s hand, like clay in the hand of the potter.
In this state of defective submission to the divine will,
they are not in a capacity duly to appreciate the benefits
resulting from a practical faith in the name of the Son of God.
Their views and dependence being outwardly directed,
are limited to a merely literal explanation of this holy name;
they do not therefore clearly perceive the necessity of
seeking and waiting for divine influence,
to effect the needful preparation of heart before him,
previous to the offering of their prayers at the throne of grace.
And if in their assemblies for divine worship they are
not gathered together in the name of Christ,
can it be expected that he will be in the midst of them? (See Matt.
18:20) The necessity of the influence of the Spirit of Christ,
in this solemn engagement of worship, is fully acknowledged by the Apostle Paul; for,
notwithstanding his extraordinary gifts,
and large experience in the ministry of the Gospel, he declares,
respecting himself and his fellow-believers,
"`Likewise the Spirit also helpeth our infirmities:
for we know not what we should pray for as we ought;
but the Spirit itself maketh intercession for us,
with groanings which cannot be uttered;`" (Rom. 8:26) that is, as a late writer^
footnote:[Priscilla H. Gurney]
observes, "`with fervent internal aspirations,
the sensible effect of that powerful cause,--
even the silent operation of the Spirit of truth;
showing unto man, from time to time, his real condition; and teaching him immediately,
both what to pray for, and how to pray aright.`"

By Him, Jesus Christ, let us then worship and serve God "`in newness of Spirit,
and not in the oldness of the letter;`" (Rom.
7:6) believing in his name,--even in that name,
which God hath exalted above every name, "`that at`" or in^
footnote:[J. G. Bevan`'s [.book-title]#Life of Paul,# note, page 363.]
"`the name of Jesus, every knee should bow, of things in heaven, and things in earth,
and things under the earth; and that every tongue should confess,
that Jesus Christ is Lord, to the glory of God the Father.`"
(Phil. 2:10-11) Were the true bowing at the name of Jesus understood,
and witnessed in our hearts,--were we so humbled by his power,
as to submit to his government, however contrary to our former views and practices,
the performance of our religious, as well as of our moral duties,
being brought under his holy influence and control, we should be Christians indeed;
we should be able in truth to address Jesus Christ as
our Lord;--his holy light being our Leader,
and his holy will, made known to us thereby, being done in and by us in all things.
Thus would the name of Jesus be "`exalted above every`" other "`name,
to the glory of God the Father.`"

In the opening of this chapter, reference is made to those merely nominal Christians,
who, rejecting the admonitions of the light of Christ,
refuse to enter the path of self-denial, and are consequently disqualified,
while they persist in their disobedience,
for the performance of that worship which is in spirit and in truth.
In pursuing this subject, it is designed to show the necessity,
not only of entering "`in at the strait gate,`" but also of
continuing "`to walk in the narrow way,`" bearing the cross daily,
and following Christ;
that the Christian traveller may be preserved from taking up a rest in his own works,
confiding in a form of godliness, without its life and power.
May a sense of this danger deeply impress the minds of such religiously disposed persons,
as have been addressed in several preceding paragraphs of this chapter.
In order to place the subject before them in a clear point of view,
their attention is solicited to the following observations,
founded principally on this precept of our Redeemer--of Him, let us ever remember,
whom our heavenly Father has commanded us to hear:
(Matt. 17:5) "`If any man will come after me,`"--in other words,
if any man will be a Christian indeed,--"`let him deny himself,
and take up his cross daily, and follow me.`"
(Luke 9:23) The effects which result from faithfully persevering in this course, which,
we must acknowledge, our Savior himself has pointed out to us,
are thus briefly described by the Apostle Paul: "`I am crucified with Christ;
nevertheless I live; yet not I, but Christ liveth in me:
and the life which I now live in the flesh, I live by the faith of the Son of God,
who loved me, and gave himself for me.
(Gal. 2:20) This eminent minister of Christ not only
witnessed the mortification of the flesh in his own person;
but also enforced it on those among whom he labored, in the following emphatic language:
"`This I say then, walk in the Spirit, and ye shall not fulfill the lusts of the flesh;
for the flesh lusteth,`" or striveth "`against the Spirit,
and the Spirit against the flesh; and these are contrary the one to the other.`"
(Gal. 5:16-17) And in order to convince us,
that walking in the Spirit and bearing the daily cross,
are absolutely necessary to our becoming true Christians, he declares,
"`They that are Christ`'s, have crucified the flesh, with the affections and lusts.`"
(Gal. 5:24)

This observation of the Apostle,
respecting the conflict which takes place between the Spirit and the flesh,
may be considered applicable to all mankind,
however diversified as to religious profession.
Now whichsoever of these, (the Spirit or the flesh) we join with and obey,
by this are we influenced and governed,--"`His servants ye are to whom ye obey,
whether of sin unto death, or of obedience unto righteousness.`"
(Rom. 6:16) The Spirit prompts us to deny self,
to crucify the flesh by taking up our cross daily, and to follow Christ;
its purifying effects in our hearts being evinced, by our living "`soberly, righteously,
and godly, in this present world.`"
And if this divine instructor in its further manifestations in our hearts be obeyed,
through the ability which it imparts,
it will enable us "`to worship the Father in spirit and in truth.`"
But the tempter, through the medium of the flesh,
strives in various ways to obstruct and prevent these most desirable results.
When his efforts are ineffectual to draw awakened minds back
again into their former habits of gross irreligion and sin,
he then employs a more insidious snare, by assuming a religious character,
and making a specious show of piety and devotion; but still opposing the Holy Spirit,
by endeavoring, through deceptive insinuations,
to prevent its salutary admonitions from being listened to and obeyed.
In particular, he strives to excite,
and to foster in the minds of many professed Christians,
an aversion to the duty of "`Watching;`" (Eph. 6:18; Mark 13:37-14:38; Col. 4:2) under which, that of patient waiting for the Lord,
in the exercise of faith and love, appears to be included; (see Hos. 12:6; Isa. 40:31;
Ps. 40:1) a duty mercifully designed as the means, by which, in stillness^
footnote:["`Be still, and know that I am God.`" (Ps. 46:10)]
(weak and feeble and liable to be misled as we all are of ourselves,)
the sincere in heart may hear the voice of the "`good Shepherd,`" and
may receive from him instruction to perceive,
and strength to avoid temptation,
and ability also to offer up their prayers in His holy name, to their heavenly Father.
But the enemy, through the carnal mind, suggests doubts,
whether this duty of watching be really obligatory; and it may be apprehended,
that in order effectually to divert the professors of religion from the practice of it,
he prompts them to place their dependence on their own wisdom and activity,
rather than to submit to so self-denying an exercise of mind.
In all cases, in which these insinuations are embraced and followed,
the secret monitions of the spirit of Christ become gradually disregarded;
darkness then ensues; and of course,
the great work of purification of heart is obstructed.
They seek, and soon find, a way to walk in,
that is more agreeable to the natural will and the pride of the human heart,
than that in which the denial of self,
and the patient bearing of the daily cross are required.
Their faith standing not in the power of God, but in the wisdom of men;
(1 Cor. 2:5) they are frequently running after this or the other eloquent minister,
not regarding the declaration of Christ--"`the kingdom of God
is within you;`" nor seeking (the manifestation of) this
kingdom and the righteousness of God according to his command:
(Matt. 6:33)--as they go on in this course, they become, in very many instances,
strongly attached to forms and ceremonies,
set up and enjoined by human wisdom and authority;
and thus they are led into the practice of will-worship.

Alas! how greatly is the brightness of genuine Christianity obscured in the present day,
among very many professors of it;
through their not duly watching against and avoiding
the influence and efforts of the carnal mind,
in every form, under which it opposes, and strives against the Spirit of Christ.
They will probably admit that watchfulness is requisite,
as a preservative from the violation of the precepts of morality,
in their general conduct and conversation; but they appear not to be sufficiently aware,
that it is especially necessary in regard to the
Worship which they offer to Almighty God:
for in this solemn engagement,
as far as they are led by the activity of self or the flesh,
so far are their minds disqualified for the reception
of the life-giving influence of the Spirit of Christ,
through which alone the acceptable worship, which is in spirit and in truth,
can be offered.
So that however ardent their zeal may be in devotional exercises,
and however delightful the animation it excites, yet,
if the influence by which they are actuated in their worship,
be not that of the Spirit of Christ, the conclusion seems inevitable,
that it proceeds from self or the carnal mind.

How needful then is it, for professed Christians of every denomination,
under a conviction of the great danger in which a
mistake in this important concern would involve them,
to lay open their hearts, in all humility and sincerity,
to the discriminating ray of the light of Christ,-- to that standard,
to which the Apostle directs our attention;--"`All things that are reproved,
are made manifest by the light,
for whatsoever doth make manifest is light;`" (Eph. 5:13) that, under its direction,
they may be enabled to form a true judgment,
as to the influence which hath obtained the government in their minds.
The sad consequences of continuing to act under the
influence of that which opposes the Spirit of Christ,
may be inferred from these words of the same Apostle: "`To be carnally minded is death,
but to be spiritually minded is life and peace;
because the carnal mind is enmity against God, for it is not subject to the law of God,
neither indeed can be;
so then they that are in the flesh`" (they in whom the carnal mind predominates)
"`cannot please God;`" (Rom. 8:6-8) to which it may be added,
that however highly they may characterize their religious attainments,
yet while they remain in this state,
they are incapable of participating in that fellowship,
which is "`with the Father and with his Son Jesus Christ.`" (1 John 1:3)

In reverting to the description which the Apostle gives of his own experience,
already quoted, let us take into view what he says in another place,
on the same important subject: "`Know ye not,
that so many of us as were baptized into Jesus Christ, were baptized into his death;
therefore we are buried with him by baptism into death;
that like as Christ was raised up from the dead by the glory of the Father,
even so we also should walk in newness of life: knowing this,
that our old man is crucified with him, that the body of sin might be destroyed,
that henceforth we should not serve sin.`"
(Rom. 6:3-5) By thus conforming to the doctrine of his Lord,
in bearing the daily cross, and by submitting to the baptism of the Holy Spirit,
the Apostle was enabled to say, "`I am crucified with Christ, nevertheless I live,
yet not I, but Christ liveth in me.`"

May all professed Christians be stimulated and encouraged to
press forward to the attainment of this state,^
footnote:[Let it not be supposed that the high privileges
which the Christian dispensation holds out to mankind,
do not comprise the attainment of this state.
Our Lord Jesus Christ prayed to the Father,
not only on behalf of his immediate followers,
but for them also which should believe on him
through their word,--"`That they all may be one,
as thou, Father, art in me, and I in thee, that they may be one in us.
I in them, and thou in me,
etc.--concluding his supplication (which should
be read with reverence and awe) in these words:
"`I have declared unto them thy name, and will declare it;
that the love wherewith thou hast loved me, may be in them, and I in them.`"
(John 17:20,21,23,26)]
according to the measure of divine light or grace severally dispensed to them.
May they be so humbled by the power of God,
as to become willing to "`deny self,`" "`the
flesh,`" or "`the carnal mind;`" in other words,
to "`put off the old man with his deeds;`" (Col. 3:9)
not only his grossly corrupt and sinful practices,
but also his acts of devotion, his praying and singing,
and (in respect to ministry) his preaching too.
Then will they be enabled, by following Christ in the regeneration,
(Matt. 19:28) to "`put on the new man;
which after God is created in righteousness and true holiness.`"
(Eph. 4:24) They will become true worshippers, like the believers formerly,
worshipping God in the Spirit, rejoicing in Christ Jesus,
and having no confidence in the flesh. (Phil. 3:3)

The Scriptures declare, that "`as many as are led by the Spirit of God,
they are the sons of God;`"
(Rom. 8:14) and that "`the manifestation of the
Spirit is given to every man to profit withal.`"
(1 Cor. 12:7) How desirable, how indispensable then is it, that all,
and especially those who call themselves ministers of Christ,
should follow the puttings forth and leadings of his Spirit in their own minds.
The teaching of the Spirit of Christ is always
in accordance with his doctrines and precepts,
which are presented to us in the Scriptures; so that those who are in office,
as ministers of Christ, if they be truly such, and be indeed led by his Spirit,
will evince, not only in their conduct and conversation, but also in their ministry,
a faithful adherence to that portion of his doctrine already adverted to,
enjoining the denial of self, the taking up the daily cross, and the following of him.

But if any who undertake the office of a Christian minister,
evince in their general deportment, a disposition to evade the denial of self,
to shrink from bearing the cross,
and from putting "`off the old man with his deeds;`" (Col. 3:9)--if,
instead of following the Spirit of Christ, in their ministry,
they follow the suggestions of their own "`fleshly wisdom,`" (2 Cor. 1:12)
"`teaching for doctrines the commandments of men,`" (Matt. 15:9)
his own declaration seems to authorize the conclusion,
that their worship is "`in vain.`"
And when any of those, who,
declining the use of the modes and forms of worship prescribed by human authority,
profess to depend on the direction of the Spirit of Truth,
do not wait in humility of mind for its life-giving influence, but in their self-will,
under the impulse of creaturely zeal,
undertake to preach or to pray in their public assemblies, these performances,
like the offering of strange fire under the Mosaic dispensation,
(Lev. 10:1) may be considered to be in an
especial manner offensive in the divine sight.
In all these cases, unless they submit to that divine word,
which is said to be "`like a hammer that breaketh the rock in pieces,`"
(Jer. 23:29) and unless by its effectual operation they are
brought to the experience of true humiliation and contrition,
and through repentance witness purification of heart from pride and exaltation of self,
they are in danger of becoming like unto some formerly,
of whom we read,--that they "`shut up the kingdom of
heaven against men;`" neither going in themselves,
nor suffering "`them that are entering to go in.`"
(Matt. 23:13) And if they persist in this course,
disregarding the convictions of the Spirit of Christ, which,
from the time when they began to reject its admonitions in their own consciences,
it may be presumed, has not failed at seasons still to reprove them,
they will become more and more "`laden with iniquity;`" and by thus
continuing in the transgression of the law written on the table of the heart,
there will be much ground for them to fear,
however successful they may esteem their ministerial labors,
that ultimately their portion will be with those,
concerning whom our Holy Redeemer has declared, "`Many will say to me in that day, Lord, Lord,
have we not prophesied (or preached) in thy name? and
in thy name have cast out devils? and in thy name done
many wonderful works? And then will I profess unto them,
I never knew you: depart from me, ye that work iniquity.`" (Matt. 7:22-23)
