[#chapter_3, short="Baptism, Worship, and Partaking of the Flesh and Blood"]
== Chapter III: On Baptism.--Continuation of the Subject of Divine Worship, in Connexion with Observations on the Partaking of the Flesh and Blood of Christ.

The qualifications requisite for admission into the church of Christ,
do not comprise the observance of any of the types, ceremonies, and carnal ordinances,
of the Mosaic dispensation, or of that of John the Baptist; which were fulfilled,
and abrogated by the Son of God, in his personal appearance and death on the cross.
But the Apostle Paul plainly declares, that, "`if any man have not the Spirit of Christ,
he is none of his;`" (Rom. 8:9) that is,
if any man have not accepted the Spirit of Christ for his teacher, his baptizer,
and his sanctifier, but on the contrary, in respect of these offices,
have disregarded and rejected him,
this man is not Christ's. Whatever may be his profession or performances, as to religion,
whether he be a member of the 'Established Church,' or a dissenter from it,
he is not a member of the spiritual body or church, of which Christ is the Head.
For according to the doctrine of the same Apostle, the baptism,
by which believers are introduced into this church, is the baptism of the Spirit;
(1 Cor. 12:13) consequently it is not that of water,
applied either by sprinkling or immersion.
The baptism of the Spirit is an inward work; and it should never be forgotten,
that it is not the body, but the soul of man, that is the subject of it.


John the Baptist makes a very clear distinction between his baptism with water,
and the baptism of Christ: "`I indeed (said he) baptize you with water unto repentance;
but he that cometh after me is mightier than I, whose shoes I am not worthy to bear,
he shall baptize you with the Holy Ghost and with fire:`" (
Matt. 3:11) and a similar and equally clear description of
the two baptisms is given by our Lord himself.
(Acts 1:5) This baptism with the Holy Ghost,
is that which has been already adverted to in the first chapter of this pamphlet.
It is the work of the Spirit of Christ operating in the soul of man,
principally immediately, but sometimes also instrumentally by the ministry of the Gospel.
This baptizing ministry appears to have been instituted by Jesus Christ himself;
we do not find that he gave any commission to his disciples to baptize with water,
or that he so baptized any one himself.
We read that after his resurrection, he declared to them,
"`All power is given unto me in heaven and in earth,`"
adding "`Go ye therefore and teach all nations,
baptizing them in the name (the divine power and life) of the Father, and of the Son,
and of the Holy Ghost.`"
(Matt. 28:18-19) Of this baptizing ministry,
we have an instance in the account which the Apostle
Peter gives of his visit to the family of Cornelius:
"`As I began to speak,`" said he,
"`the Holy Ghost fell on them as on us at the beginning:
then remembered I the word of the Lord; John indeed baptized with water,
but ye shall be baptized with the Holy Ghost.`"
To this the Apostle added, "`God gave them the like gift as he did unto us.`"
(Acts 11:15-17)

Thus the gift of the Holy Spirit appears to have accompanied the preaching of Peter,
and was communicated independently of water-baptism;
although this Apostle was not then fully weaned
from an attachment to this typical ordinance;
for it appears that in this case of early Gentile conversion,
he directed it to be administered to them, who had previously received the Holy Spirit;
(Acts 10:47-48) although under a doubt, which the enquiry,
"`Can any man forbid water,`" etc. seems to imply.
In process of time, however, this eminent Apostle's views on the subject of baptism,
appear to have been enlarged; for we find, that in his general epistle,
describing the baptism by which believers are now saved, he declares,
it is "`not the putting away the filth of the
flesh,`" (which is the proper effect of baptism,
or washing, in water,) "`but the answer of a good conscience toward God,
by the resurrection of Jesus Christ.`"
(1 Peter 3:21) Now this is a description of the
effect of Christ's baptism with the Holy Spirit,
and with fire; by which a death unto sin, and a new birth unto righteousness,
through faith in that divine power, by which Christ rose from the dead, are witnessed;
and thus the answer or testimony of a good conscience is produced.
The Apostle Paul's language on this subject is also very instructive:
having adverted to the mystery which hath been hid from ages and generations,
but now is made manifest to the saints, which (saith he) "`is Christ in you,
the hope of glory; whom we preach, warning every man,
and teaching every man in all wisdom,
that we may present every man perfect in Christ Jesus;`" he then proceeds,
"`As ye have therefore received Christ Jesus the Lord,
so walk ye in him;`"--"`and ye are complete in him,
which is the head of all principality and power;`"--"`buried with him in baptism,
wherein also ye are risen with him, through the faith of the operation of God,
who hath raised him from the dead.`" (Col. 1:26-28; Col. 2:10,12,6)
"`Therefore we are buried with him by baptism into death;
that like as Christ was raised up from the dead by the glory of the Father,
even so we also should walk in newness of life.`"
(Romans 6:4) This is that one baptism of which the Apostle speaks, (Eph. 4:5:
"`There is one body and one Spirit, one Lord, one faith,
one baptism;`" and describing the agent in this important work,
(whether commenced through the medium of instrumental ministry, or not,) he declares,
"`By one Spirit are we all baptized into one body,`" or Church of Christ;
"`and have been all made to drink into one Spirit.`" (1 Cor. 12:13)

The terms "`water`" and "`fire`" are used in the New Testament,
in reference to the baptism of Christ, and to the new birth,
which is the effect of this baptism.
It is said of Christ, "`He shall baptize you with the Holy Ghost and with fire.`"
(Matt. 3:11) Again we read, "`Except a man be born of water and of the Spirit,
he cannot enter into the kingdom of God.`"
(John 3:5) But these terms, in the texts quoted, are not to be understood literally,
but figuratively.
As the property of water is to cleanse, and that of fire to refine,
so the baptism of Christ cleanses and refines the soul which submits to it,
from the stains and dross of sin.

In the apostolic age, although the baptism of Christ, when administered instrumentally,
by the preaching of the Gospel, was in many instances accompanied by miraculous gifts;
yet we have no ground to conclude now, in the absence of such gifts,
that a measure of the same baptizing influence of the
Spirit does not still accompany the ministry of those,
whom he calls, qualifies, and employs in his service; and who act therein,
only under his ministration and guidance, in an humble dependence on his wisdom,
life and power.
Through the gracious continuance of divine mercy and love,
this influence is yet witnessed, in a greater or less degree, when the word,
thus preached, is "`mixed with faith`" in them that hear it. (Heb. 4:2)

Some of the advocates of water baptism lay much stress on
those instances which are recorded in the New Testament,
in which some of the Apostles appear to have used, or to have directed the use of,
this typical ordinance.
But when it is considered that some of the Apostles for awhile
after the crucifixion and ascension of our Holy Redeemer,
were in the practice not only of water baptism,
but also of some other typical ordinances, viz.
circumcision, etc.;
there appears no valid reason why their practice with respect to water baptism,
should be considered more obligatory on the Christian church at the present day,
than their practice with respect to circumcision, and some other Mosiac rites.
'On a view of the whole matter, there appears sufficient ground for the conclusion,
that it was permitted by divine wisdom,
that the typical ordinances of the preceding dispensations,
(of Moses and of John,) although virtually abrogated by the death of Christ on the cross,
should not in the infantile state of the Church be laid aside suddenly, but gradually,
as the minds of the Christian converts became capable of more clearly
comprehending the spiritual character of the Christian dispensation.
It is therefore earnestly recommended to all those, whose minds are so far enlightened,
as to see clearly that something more than the mere name or
outward profession of Christianity is absolutely necessary,
that in seeking to become in reality members of the church of Christ,
and sheep of his fold,
they do not endeavor to climb up through the ways which human wisdom may uphold,
by a recurrence to the use of any of the types or ordinances of former dispensations,
which were fulfilled and abrogated by the coming and death of Christ,
as the Scripture declares: (Heb. 9:8-11; Col. 2:14,16,17)
for Christ is the door of the true sheep-fold, or church;
(John 10:9) and they who become members of it, must enter in by faith in him,
and by submission to the baptism of his Holy Spirit. (1 Cor. 12:13)

They who thus become members of the true church of Christ,
are permitted to witness its blessed privileges.
They partake of that divine food, which he describes as his flesh and blood;
and this food is so necessary for their preservation and growth in true religion,
that he declared, "`Except ye eat the flesh of the Son of Man, and drink his blood,
ye have no life in you.`"
(John 6:53) Some who heard him speak these words, thought then,
as many professed Christians appear to think in the present day,
that this declaration should be understood as relating
to the flesh and blood of his outward or material body.
Our Lord, however, graciously condescended to correct this mistake:-- may every one,
who has adopted this,
or any other outward signification of the words of Christ now under notice,
very seriously reflect upon and accept, the explanation which He gave,
on this highly important subject.
After it had been queried,
"`How can this man give us his flesh to eat?`" this was his reply:
"`It is the Spirit that quickeneth.`"
Surely then, if it be the Spirit that quickeneth, or giveth life,
it should be concluded,, that it was the partaking of the quickening,
life-giving influences of his Holy Spirit,
diffused in the soul,--He dwelling in us and we in him,
(v. 56,) which he designed to represent under the terms,
eating his flesh and drinking his blood, without which we have no life in us.
And it seems,
as if it were in order to place this important point beyond the risk of mistake or doubt,
that after he had said, "`It is the Spirit that quickeneth,`" he immediately added,
"`the flesh profiteth nothing; the words that I speak unto you,
they are Spirit and they are life.`" (John 6:63)
The doctrine of the Apostle Paul, on this very important subject,
is in perfect unison with that of his divine Master.
In his Epistle to the Corinthians, he declares that "`the Spirit giveth life.`"
(2 Cor. 3:6) It also appears, from his first Epistle to the same church,
that long before the incarnation of Christ,
some of the Israelites partook of that spiritual meat and drink,
which are derived from him; for the Apostle declares,
"`they did all eat the same spiritual meat, and did all drink the same spiritual drink;
for they drank of that spiritual rock that followed them, and that rock was Christ.`"
(1 Cor. 10:3-4)

If the followers of Jesus Christ could have been
permitted to eat the flesh of his material body,
it is evident, from his own words, that it would have profited them nothing.
It was the life-giving influence of his Holy Spirit,
by which alone those who believed on him in that day, were made alive,
and preserved "`alive unto God.`"
(Rom. 6:11) And in the present day,
the same divine influence produces similar effects, in the souls of all those, who,
believing in the light, life, and power of Christ, receive him for their Teacher,
Savior, Priest, and King; believing also, if they have access to the Holy Scriptures,
all that those sacred records declare, respecting the sufferings and death of Christ,
and the benefits resulting therefrom to mankind.
These partake of the true supper of the Lord; as it is written, "`Behold,
I stand at the door`" (of the heart) "`and knock; if any man hear my voice,
and open the door, I will come in to him, and will sup with him, and he with me.`"
(Rev. 3:20) This divine food is essentially the same as that
which our Holy Redeemer described under other figurative terms; viz.
as the bread which cometh down from heaven, and giveth life unto the world;
(John 6:33) as "`living water,`" which, in them who drink of it,
should be as a "`well of water, springing up into everlasting life.`" (John 4:10,14)

Amidst the manifold mercies which they partake of, who, through divine grace,
witness an advancement in the work of regeneration,
this communication of spiritual food to their souls,
should ever be gratefully acknowledged.
Like the sap, that enables the branches which abide in the vine, to bring forth fruit,
so the quickening, life-giving influence of the Spirit of Christ,
who is the "`true vine,`" (John 15:1) enables those who, as branches, abide in Him,
to bring forth the fruits of the Spirit, which are,
"`in all goodness, and righteousness, and truth.`" (Eph. 5:9)
For under His holy influence,
they are incited and strengthened from day to day to maintain,
even in their temporal concerns, a strict adherence to justice, truth, and equity,
doing unto others, as they would that others should do unto them.
Their words and actions being leavened by Christian purity, sincerity, humility,
and love, they exemplify, as their growth in the divine life progresses,
not only in their own families, but amongst all with whom they associate,
the powerful efficacy of that holy name, in which they have believed,
and into which they have been baptized.

If we seriously recur to those solemn declarations of our Lord Jesus Christ,
"`Except ye eat the flesh of the Son of Man, and drink his blood,
ye have no life in you;`" "`He that eateth my flesh, and drinketh my blood,
dwelleth in me and I in him;
(John 6:53,56) and if we keep in view the clear explanation
which he condescended to give of these words,
the conclusion must surely be admitted, on the highest authority,
that whatever may be our religious profession,--however
largely our minds may be furnished with the literal knowledge
of the doctrines and precepts of the Holy Scriptures,
or our memories charged with the recorded experience of good men of ancient
and modern times,-- and however highly we may think of ourselves,
or be esteemed by others, on this or on any other account; yet,
if we do not partake of the quickening influences of the Spirit of Christ,
we have no life in us;--we dwell not in Him,
nor He in us;--and consequently we are more or
less in a state of spiritual darkness and death.
A conviction of the vast importance of this subject, induces the writer, under,
he trusts, some degree of the constraining love of Christ,
to press it upon the close attention of those,
with whom he is connected in religious profession,^
footnote:[The Society of Friends.--The writer wishes to state,
that the Society is not responsible for any thing contained in these pages.]
as well as upon Christians of every other denomination.

Having endeavored, in the preceding pages, to point out the means whereby the soul,
through the obedience of faith,
may attain to a capacity of partaking of this divine food,
and to show the necessity and benefits thereof,
it may be proper in the next place to make some further observations,
with respect to its communication and effects.

The great Head of the church dispenses this heavenly
sustenance to the living members of his body,
in their religious assemblies, sometimes by the instrumental ministry of the gospel,
at other times by the immediate effusion of his Holy Spirit upon their minds, when,
it may be, the assembly is in a state of solemn silence, and reverent waiting before Him.
They are also permitted to enjoy this privilege from time to time,
in seasons of private retirement; and even day by day,
whilst engaged in their lawful occupations, if,
feeling the want of the enlivening influence of the Spirit of Christ,
they humbly seek it.
It is pre-eminently for this divine nourishment--for this bread "`
that cometh down from heaven,`" that our blessed Savior teaches us
to pray to our heavenly Father,--"`Give us this day our daily bread.`"
When favored in their public assemblies to witness the gracious promises fulfilled,
that, "`They that wait upon the Lord shall renew their strength,`" (Isa. 40:31)
and that where even two or three are gathered together in His name,
there, He, who is "`a quickening Spirit,`" (1 Cor. 15:45) even the Lord Jesus Christ,
is in the midst of them; (Matt. 18:20) they can thankfully acknowledge, that,
although the baptizing ministry of the gospel is
a great blessing to the church of Christ,
and should be received with feelings of gratitude to the Source of all good;
yet it is a higher privilege to be fed immediately by Himself,
the holy Head of the church and Bishop of souls,
than through the instrumentality of their fellow-members.

The solemn declaration of our Holy Redeemer to
the woman of Samaria on the subject of worship,
should indeed make a deep and awful impression upon the minds of all who
profess to prostrate themselves before the Most High! "`God is a Spirit,
and they that worship him, must worship him in Spirit and in truth.`"
And again he said;
"`No man cometh unto the Father but by me;`"--and "`without me ye can do nothing.`"
How needful then must it be, in order to perform this worship,
that the mind be brought into a state of entire humiliation,--bowed
down under a true sense of its great weakness,--of its many wants,
and utter unworthiness,--accompanied with a conviction
of the perfect purity of that Almighty Being,
whose sacred presence is unapproachable, except through our Holy Mediator,
the Lord Jesus Christ.
Perhaps it may be said,
that there is no other engagement in which the religiously
exercised mind is so fully penetrated by these feelings,
as in that of silent waiting upon God in assemblies for public worship.

But although Christ is always in some measure present with those, who,
through the baptism of his Holy Spirit, are members of his church; yet,
according to the experience of many who are of this description,
he is frequently pleased to withhold from them, for a season,
in their religious assemblies, as well as at other times,
that increased communication of his power and life,
which is needful to qualify them for the performance of the solemn act of divine worship.
Yea, for a wise and gracious purpose,
he oftentimes permits them to feel how weak they are of
themselves,-- how utterly insufficient by their own strength,
to resist the efforts of their soul's adversary; who,
by exciting the natural propensity to be occupied with terrestrial objects,
or by presenting to the imagination creaturely ideas relative to worship or doctrine,
often endeavors to draw off their minds from that denial of self--
that subjugation of their own will and wisdom--which are requisite in
order to wait patiently upon God in the exercise of faith and love.
But although He,
the good "`Shepherd and Bishop of souls,`" (1 Pet. 2:25) may
permit those humble believers in him to be thus tried and proved,
yet he does not forsake them:-- in his own time,
(for which with fervent desire they reverently wait,) the enlivening,
purifying influence of his Holy Spirit imparts fresh vigor to their souls:
thus strengthened, they surmount those impediments, of what kind soever,
which had obstructed their access "`unto the throne of grace;`" (Heb. 4:
16) and they are enabled to "`draw near in full assurance of faith.`"
(Heb. 10:22) The worship thus offered in religious assemblies,
whether it be accompanied with vocal ministry, prayer, or praise,
in obedience to the will of the great Head of the church,
immediately communicated to such of its members as he may see meet to
employ in his service,--or whether in obedience to the same holy will,
it wholly consists in silent^
footnote:[It must not be supposed, that all,
who are in the practice of sitting in silence, in assemblies for public worship,
are benefited in the manner above described.
It is only the awakened mind,--the mind in which
the work of regeneration is in some degree begun,
that is capable of truly waiting upon God in silence,
under an exercise of faith and love towards him.
Yet there is ground to believe, that in numerous instances,
persons who have previously evinced little or no concern about their soul's salvation,
being induced, some of them probably by mere curiosity,
to enter a silent religious assembly, have been awakened,
and their minds greatly contrited by the divine power;
although not a word has been spoken in the assembly.
And this visitation of the love of the Redeemer,
has proved the commencement of the effectual working of his grace in their souls.]
aspirations, arising from quickened souls,
in a state of reverent prostration before the throne of grace,--in either case,
this worship does not fail to meet the divine acceptance.

Although many individuals, in whom the work of regeneration has been begun,
and who are in the practice of waiting upon God in assemblies for public worship,
may not always receive such a supply of spiritual food,
as the apprehension of their own need leads them to expect;
yet may these not be discouraged: may they duly consider,
that the Lord knows better than they do, what is best for them.
He knows what will conduce to the progress of that great work,
which he has begun in their souls.
For a wise and benign purpose,
he introduces his children into a state of poverty of spirit;
the tendency of this discipline being to increase their faith,
and to establish them more firmly on Himself,
the "`sure foundation,`"--"`the Rock of Ages.`"
Therefore, ye who hunger and thirst for the bread and water of life,
be not dismayed on account of the apparent smallness of the portion sometimes,
yea frequently, dispensed unto you.
Should it be no more, figuratively speaking, than a crumb of this bread,
or a drop of "`living water,`" yet, if received with thankfulness,
it will be found sufficient for the present need,--sufficient to strengthen
you still to trust in the Lord,--still to wait upon him in faith,
and with a lively hope in his goodness and mercy;
and whenever these effects are witnessed, they should be considered as an evidence, that,
through the gracious regard of your heavenly Father,
a portion of divine aid and sustenance has been dispensed unto you.
The revival of this faith and hope, when felt, after much mental labor and conflict,
whether in religious assemblies, or in private retirement,
how precious is it to the tribulated soul!
The Lord's holy name be praised for all his mercies partaken of by those,
who are engaged,
although frequently under a feeling of many discouragements and infirmities,
to seek for ability to worship him in Spirit and in truth!
