== Forward by the Editor


I will add some text here!!

Samuel Rundell (1762 - 1848) was by trade a wool-dealer who lived in Liskeard,
a small town in southwest England.
As a young man he was recognized as a minister in
the Society of Friends (Quakers), of which he was a member.
In the course of a long ministry he often travelled
and held meetings in the county of Cornwall where he resided,
and at times made longer journeys in the service of truth,
visiting Scotland, Ireland, and elsewhere;
and he was a frequent attender of the annual Yearly Meeting in London.

Throughout his life he was particularly concerned to press the necessity of a
real and living experience of inward purification by an unreserved obedience
to the light or Spirit of Christ working in the heart.
Having witnessed its effectual operation in his own soul,
he greatly desired to see this scriptural doctrine both upheld amongst his
fellow Quakers and more widely known among sincere Christians of every denomination.

The book you are reading came out from that lifelong concern,
and was first published in 1834 when Rundell was 72 years old.
This edition has been minimally and carefully
modernized with the goal of making this valuable work
somewhat more accessible for today`'s readers without changing
the author`'s meaning or over-modernizing the original language.
All footnotes are Rundell`'s, unless labeled __Editor`'s Note__.

[.signed-section-signature]
Jared Henderson

[.signed-section-context-close]
September, 2018
