== Forward by the Editor

Samuel Rundell (1762 - 1848) was by trade a wool-dealer who lived in Liskeard,
a small town in southwest England.
As a young man he formed a valuable friendship with
the aged William and Catherine (Payton) Phillips,
who at that time lived in nearby Redruth.
At the age of 28 he first spoke in a meeting of the Society of Friends (Quakers),
of which he was a member,
and within a few years he was recognized officially as a minister by his monthly meeting.

In the course of his long ministry he frequently travelled
and held meetings in the county of Cornwall where he resided,
and at times made longer journeys in the service of truth,
visiting Scotland, Ireland, and elsewhere,
and was a frequent attender of the annual Yearly Meeting in London.

In his ministry he was particularly concerned to press the necessity of a
real and living experience of inward purification by an unreserved obedience
to the light or Spirit of Christ working in the heart.
Having witnessed its effectual operation in his own soul,
he greatly desired to see this scriptural doctrine both upheld amongst his
fellow Quakers and more widely known among sincere Christians of every denomination.

This book you are reading came out from that lifelong concern,
and was first published in 1834 when Rundell was 72 years old.
This edition was prepared by minimally modernizing the second edition,
which appeared in 1838.
My goal in updating the text for this edition was to make this valuable work
somewhat more accessible for modern readers without anywhere changing
Rundell’s meaning or over-modernizing his original language.
The vast majority of changes made consisted in updating archaic pronouns,
modernizing punctuation, and carefully replacing a small number of
words or phrases which are no longer used or whose meaning has changed.
Additionally, some lengthy paragraphs were broken up at logical points,
and a few extremely long sentences were divided or slightly rearranged
to be more manageable for today’s reader.
All footnotes are Rundell’s, unless labeled __Editor’s Note__--these are mine.

[.signed-section-signature]
Jared Henderson

[.signed-section-context-close]
September, 2018
