== Chapter I: On Conversion and Regeneration

When our Lord Jesus Christ was transfigured on the mount,
the voice from the excellent glory bore witness of Him, saying, "`This is my beloved Son,
in whom I am well pleased; hear Him!`" (2 Pet. 1:17, Matt. 17:5)
He, whose doctrine we are thus commanded to hear, and of course reverently to embrace,
declared:

[quote.scripture]
____
(John 3:16) "`God so loved the world, that He gave His only begotten Son,
that whoever believes in Him should not perish but have everlasting life.
(3:17) For God did not send His Son into the world to condemn the world,
but in order that the world through Him might be saved.
(3:18) He who believes in Him is not condemned,
but he who does not believe is condemned already,
because he has not believed in the name of the only begotten Son of God.
(3:19) And this is the condemnation, that the light has come into the world,
and men loved darkness rather than light, because their deeds were evil.
(3:20) For every one who does evil hates the light, and does not come to the light,
lest his deeds should be reproved.
(3:21) But he that does the truth comes to the light,
that his deeds may be made manifest, that they have been done in God.`"^
footnote:[In the 16th verse of the above quotation,
faith in the Son of God is set forth as necessary for obtaining everlasting life.
In the 18th verse, condemnation is represented as the result of unbelief in His name.
In the 19th and 20th verses, the cause of condemnation is more particularly described,
being declared to consist in not loving, but rather hating
(which of course includes not believing in) the light.
Therefore it appears that in this very important passage of Scripture,
_the light_ should be regarded as the spiritual
manifestation of the Son of God in the soul of man, for Christ said
"`I am the light of the world.`" (John 8:12)
The light may also be considered as one of the divine attributes
which are contained in the _name_ of the Son of God.
In taking this view of the subject,
there is no essential inconsistency in the various parts
of the doctrine of our holy Redeemer respecting the _object of faith_.
Christ, the ever blessed Son of God, is the object of saving faith.
And this faith, when first brought forth in the newly awakened soul, is very small,
even comparable to "`a grain of mustard-seed`"--yet it
is sufficient to enable its humble recipients
to believe in Christ revealed in their souls in His manifestation as "`the light.`"
Through "`the obedience of faith,`" these witness its gradual increase
and become capable of believing in all of Christ`'s other gracious offices
as set forth in the holy Scriptures, if they have access to that sacred record.
Moreover, believing in "`the light`" is expressly commanded by our Savior in John 12:36.]
____

By this highly important declaration of our holy Redeemer it is apparent
that the salvation of God through Him
is not limited to any particular class or portion of mankind; for God so loved the world
that He gave His only begotten Son "`that the world through Him might be saved.`"
The Son of God "`tasted death for every man,`" (Heb. 2:9) and His salvation is
partaken of by every one who truly and effectually _believes in His name_.
Now the _name_ of the Son of God in this and in many other places of the New Testament
appears to signify or have reference to His divine attributes--namely His power, life,
light, etc.^
footnote:[See [.book-title]#Cruden`'s Concordance under# "`Name,`"
also Barclay`'s [.book-title]#Apology,# Tuke`'s [.book-title]#Principles,#
Bates`' [.book-title]#Doctrines;# the three last under the article "`Baptism.`"]
And this light, being "`the life`" of "`the Word`" (or Son of God), is that "`true light
which enlightens every man that comes into the world.`" (John 1:4-9)

By this light shining in the hearts of all the children of men they are, at seasons,
reproved and convicted of sin--"`for all have sinned,
and come short of the glory of God.`" (Rom. 3:23)
Those who do not reject this light
are enabled to see the miserable state they are in while unregenerate,
being in bondage under the power of sin and defiled by its pollution.
Deeply humbled by this view of their own real condition, their hearts are contrited,
they are brought to repentance, and the cry arises:
"`God be merciful to me a sinner.`" (Luke 18:13)
Abiding in patient submission under the operation of the divine power
they are prepared to receive an increased manifestation of the light of the Word,
or Spirit of Christ, whereby faith (which is its fruit
and which in some degree had been previously exercised) is now more fully confirmed.
Thus the work of conversion advances in those
who do not reject the appearance of the light,
which is the free gift or "`grace`" of God.
(Titus 2:11) By the operation of His power,
the eyes of the spiritually blind are in degree opened,
and some true sensibility is imparted to their souls.
They are brought to feel more deeply the inestimable value of a Savior; and,
coming to Him in faith, through the attraction of the love of God,^
footnote:["`No man can come unto me, except the Father, which has sent me, draw him.`"
(John 6:44)]
they are favored to experience the baptism of His Spirit;
witnessing the remission of their past sins through His blood,
who is "`the propitiation for the sins of the whole world.`"
(1 John 2:2) They who thus walk in the light of Christ,
in "`the obedience of faith,`" are enabled, like the believers formerly,
"`to rejoice in God through our Lord Jesus Christ;`" by whom they receive
"`the atonement,`" or reconciliation with God. (Rom. 5:11)
Abiding under the baptism of the Spirit,
its cleansing operation progresses in their hearts.
Their motives--the secret springs to action--are purified from the alloy of sin,
even those lurking under a seemingly genuine appearance.
This process is described in the figurative language of Scripture
as a baptism "`with fire.`" (Luke 3:16)

The soul-satisfying peace and joy which these have found to result from believing in
and obeying the light or Spirit of Christ
encourage them to continue adhering to its manifestations.
They submit not only their words and actions,
but also the thoughts and desires of their hearts
to its righteous scrutiny and decision; so that every sinful thought and desire,
every idle word, and every evil deed, are brought unto judgment.
They see in this light that there is much more to be effected in their hearts
by the "`refiner`'s fire`" (Mal. 3:2) than previously they had any conception of;
and they are made sensible that this purifying process must be endured
so that the selfishness, pride and haughtiness,
with all the other evil affections and lusts
which the tempter strives to excite and foster in their hearts, may be fully subdued
and made to give place to the righteousness, the love, the purity,
the meekness, and the gentleness of Christ.
Amidst their many trials, by watching unto prayer
and by patiently waiting on the Lord in spirit, an increase of strength is received,
and they are enabled to hold on their way.
Continuing to follow the light of Christ in _the path of self-denial, taking up their daily cross_
(Luke 9:23) and not conforming themselves to the vain customs, fashions,
and maxims of this world, nor fixing their affections
on its riches or pleasures, but breaking off from
and avoiding every thing which the light discovers to be evil,
they gradually witness the progress of _the new birth_ in their souls:
old things pass away, and all things become new. (2 Cor. 5:17)
The threshing floor of the heart, figuratively speaking, becomes cleansed;
and the chaff burned up "`with unquenchable fire.`" (Matt. 3:12)
Having in this way received Christ Jesus the Lord,
He gives "`power to become the sons of God,`"
this grace being dispensed "`to those who believe on _His name_.`" (John 1:12)

The preceding description of the commencement and progress of conversion
is not meant to be an exact delineation of the steps by which _every
individual_ is conducted in whom this important work has been accomplished.
The degree of depravity by which the human character is marked
previous to conversion is much greater in some cases than in others.
Also, the repugnance of the natural disposition to submit to the
control and guidance of the light of Christ,
and thus to come under His yoke, varies greatly in different persons;
and consequently a corresponding variation may be required in the duration
and in the intensity of "`the refiner`'s fire.`"
And when individuals of a serious disposition have embraced doctrines which,
by leading them to place an undue stress on outward forms and ceremonies,
in fact obstruct their coming to Christ, their prejudices are not easily overcome;
these have to pass through a time of stripping--of breaking to pieces all those things,
however highly esteemed,
which have a tendency to prevent their receiving Christ in
the simplicity and humility of little children. (Matt. 18:3)
It may be expected therefore, under this great diversity of character,
that in the process of conversion there would be
"`diversities of operations, but it is the same God, which works all in all.`" (1 Cor. 12:6)

The foregoing view of faith in the name of the Son of God appears to have been _set
forth by Him_ in the latter part of that memorable passage of Scripture
which began this chapter.
After our holy Redeemer declared, "`He who does not believe is condemned already,
because he has not believed in the name of the only begotten Son of God;`" (John 3:18)
He then proceeded still more particularly to point out the _cause_ of condemnation.
For He immediately added:

[quote.scripture, , John 3:19-21]
____
And this is the condemnation, that the light has come into the world,
and men loved darkness rather than light, because their deeds were evil.
For every one who does evil hates the light, and does not come to the light,
lest his deeds should be reproved.
But he that does the truth comes to the light, that his deeds may be made manifest,
that they have been done in God.
____

[.no-indent]
From these words of our blessed Savior it may be inferred
that although professed Christians may be very diligent in acquiring the
literal knowledge of the doctrines contained in the holy Scriptures,
and may profess an unlimited confidence in the benefits resulting
from the sufferings and death of our Lord Jesus Christ;
yet if they persist in disregarding and rejecting the admonitions of the light
(which at times shines in their hearts
in order to deliver them from the power of sin and cleanse them from its pollution)
they do not, according to His doctrine, truly _believe in His name_,
and consequently they are in a state of condemnation.
It would indeed be a lamentable and dangerous delusion for such persons as these
to conclude that even while they remain in this state of unbelief and disobedience
that they are nevertheless cleansed and justified by the blood of Christ simply because they
profess a faith in His personal appearance, sufferings, and death.

In the text quoted above, the Savior of the world briefly,
yet in clear and emphatic language, _preached the doctrine of the light_;
showing that this divine gift is embraced and adhered to
by every one who "`does`" or walks in the path of
"`the truth;`" and that it is hated by all who do evil--who
reject it in order to escape from its convictions.
Now, these two classes comprehend all mankind; and therefore it is clear
that this divine gift is dispensed unto all.
Evil men could not hate or reject the light
if it did not in some degree illuminate their minds,
reproving them on account of their evil deeds.
Their not believing in, nor loving the light--refusing to hearken to
and to obey its admonitions--gratifying their corrupt propensities by
continuing in their evil ways,--__this__ is the ground of their
condemnation and the cause of their exclusion from that salvation,
which is by and through Jesus Christ.
On the other hand, those who walk in the paths of "`truth`" and righteousness,
in the obedience of faith, following the guidance of the light,
ordering their conduct and conversation according to its
dictates,--all who take this course and persevere therein,
are brought out from the darkness and death of our fallen nature
and are made partakers of the salvation of God, through Jesus Christ their Redeemer.
(See 1 John 1:7)

But although all mankind may be comprised in these two classes,
yet it is a truth clearly following from the doctrines of Scripture
that individuals may pass from either of these classes into the other.
Those who have begun to walk in the paths of truth and righteousness,
and even such as have made considerable advancement in a religious life, may,
by not abiding in the fear of God and in obedience to His holy will,
fall into temptation and be overcome thereby, and thus become evil doers.
(Ezek. 33:18, 1 Cor. 9:27)
So also, if individuals of the latter description--before the day of mercy passes
away--happily embrace the renewed visitations of a long-suffering and gracious God,
they may undoubtedly (through sincere repentance and faith in His Son Jesus Christ)
be cleansed from the pollution of sin
and brought into a state of reconciliation and favor with God.
Thus the declaration of the apostle to the Corinthians when describing various kinds
of evil doers will be applicable to them: "`And such were some of you;
but you were washed, but you were sanctified,
but you were justified in the name of the Lord Jesus, and by the Spirit of our God.`"
(1 Cor. 6:11)

Among other declarations of Christ in accordance with the foregoing, are these:
"`I am the Light of the world; he that follows Me, shall not walk in darkness,
but shall have the light of life.`" (John 8:12)
To some of the Jews who through unbelief
were in danger of having this divine gift taken from them He said,
"`Walk while you have the light, lest darkness overtake you.`"
"`While you have the light, believe in the light, that you may become sons of light.`"
(John 12:35-36) These declarations of Christ,
in which He represents Himself under the designation of "`the Light,`"
appear to have reference to Him principally as that divine Word,
the life of which, as the apostle declares, is "`the light of men.`" (John 1:4)
By the operation of this Word
the work of regeneration is effected in those who believe and walk in its light.
They are "`born again, not of corruptible seed, but of incorruptible,
by the Word of God which lives and abides forever.`" (1 Peter 1:23)
Thus they become children of light--in other words, true Christians.

It may further be observed that all who believe in the light of Christ
and walk in obedience to its manifestations from day to day
fully participate in the benefits procured by the sufferings and death of the Redeemer.
"`__If we walk in the light__`" said the apostle, "`as He is in the light,
we have fellowship with one another,
and __the blood of Jesus Christ His Son cleanses us from all sin.__`" (1 John 1:7)
Hence it appears that being cleansed from all sin
by the blood of Christ is the blessed privilege of those who walk in the light.

Christ is the gift of God unto mankind not only with respect to His outward
or personal appearance, sufferings, and death;
but also with respect to His spiritual manifestation in their hearts.
The Almighty declares, "`I will give You as a light to the Gentiles,
that You should be My salvation to the ends of the earth.`" (Isa. 49:6)
His salvation is freely offered unto all; but it is only partaken of by those
who in humility of mind receive and obey this manifestation of His holy light, or Spirit;
and embracing the faith, which is its fruit,
are baptized in or into the name--the life and power, of the Father, Son,
and Holy Spirit--as it is written:
"`He who believes and is baptized, will be saved.`" (Mark 16:16)
The faith of these will necessarily embrace the testimony of the holy Scriptures,
if they have access to this invaluable record, respecting the birth, life, doctrine,
miracles, death, resurrection, and ascension of our Holy Redeemer.
For the giving of the light, or Spirit of Christ,
(especially with respect to the increased measure
in which it is granted under the Christian dispensation) is
altogether to be ascribed to the efficacy of that which Christ,
in His appearance in the flesh, did and suffered for the human race.
Thus the benefits of the "`one offering,`" are not depreciated,
but are _more completely_ exalted by the doctrine of the manifestation of the Spirit,
or universal saving light and grace.

It is evidently the practice of the wicked one to endeavor, by various strategies,
to induce the children of men to shut up their hearts against the influence of the light,
or Spirit of Christ; and as far as he succeeds in this design,
so far he maintains his evil power and dominion in the world.
If for instance, the subtle adversary, in order to effect his purpose,
can so far beguile any of the professors^
footnote:[Editor`'s note: the word _professor_ is used throughout this book to refer
to one who professes or affirms a belief in something;
here it has nothing to do with teachers or scholars.
Likewise, a person’s _profession_ refers to what they believe or profess to be true,
and is not related to their employment.]
of Christianity as to instill into their minds
a secret aversion to the heart-searching manifestation of the light of Christ;
and if, by following up the advantage he has thus gained,
he can induce them to attach to this doctrine the stigma of enthusiasm, or fanaticism,
it then becomes easy for him to persuade them to disregard and to reject altogether
the admonitions of this divine teacher in their own minds,
in order that he may without restraint bring
forth his own works of darkness in their hearts.
But He who was manifested "`to take away our sins,`" was also
"`manifested to destroy`" these "`works of the devil.`"
When this blessed light of Christ is believed in
and allowed freely to shine in our hearts, the works of the adversary
at their very origin are clearly detected;
and if its warnings and requirements are embraced, we are enabled,
through the power which it imparts,
to "`overcome the wicked one`" in his various devices,
and "`to deny ungodliness and worldly lusts,
and to live soberly, righteously, and godly, in this present age.`" (Titus 2:11-12)

The great importance of this divine gift unto mankind appears very evident
in the account given of it by our Lord Jesus Christ
in the texts which have already been quoted.
The apostolic epistles also furnish corroborating testimony
by the designations under which they describe it,
and by the effects which they attribute to it.
In the epistle to the Corinthians
it is declared that "`God, who commanded the light to shine out of darkness,
__has shined in our hearts__, to give the light of the knowledge of the glory of God,
in the face (or manifestation) of Jesus Christ.
But we have this treasure in earthen vessels,
that the excellency of the power may be of God, and not of us.`" (2 Cor. 4:6-7)
The same apostle describes this divine gift also as
"`The grace of God, that brings salvation, and has appeared unto all men.`" (Titus 2:11)
He also represents it as "`the Spirit of God`" or "`of Christ;`" (Romans 8:9)
"`A manifestation whereof, is given to every man to profit with.`" (1 Cor. 12:7)
It is also called "`the anointing,`" which "`teaches all things.`" (1 John 2:27)
"`Christ in you the hope of glory.`" (Col. 1:27)
The 5th verse in the 13th chapter of 2 Corinthians is very emphatic:
"`Examine yourselves whether you are in the faith. Test yourselves.
Do you not know yourselves, that Jesus Christ is in you?--unless indeed you are reprobates.^
footnote:["`Reprobates,`" that is, not approved.]
"`All things that are reproved are made manifest by the light,`" etc. (Eph. 5:13)

In addition to the above, the following texts are also presented
as having reference to the same divine gift
using the phrase "`the Word,`" or "`the Word of God.`"
There are some professing Christians, however,
who suppose that these texts should be understood as referring to the Scriptures.
But it is apprehended that the incorrectness of this supposition will be evident
if a portion of the context of each quote be duly considered.
In that context, this phrase will be found to embrace attributes which,
it is conceived, are ascribable not to the Scriptures, but only to Christ,
who is "`the Word,`" by whom the world, and all things in it, were created. (Heb. 11:3)

The apostle Paul declares that the righteousness which is of faith speaks in this way,
"`Do not say in your heart, '`Who will ascend into heaven?`'
(that is, to bring down Christ from above) or, '`Who shall descend into the abyss?`'
(that is, to bring Christ up from the dead).
But what does it say?
'`The word is near you, even in your mouth and in your heart`'
(that is, the word of faith which we preach).`" (Rom. 10:8)
The apostle James exhorts:
"`Receive with meekness the engrafted word which is able to save your souls.`" (James 1:21)
The apostle Peter addresses the believers as those "`being born again,
not of corruptible seed but incorruptible, by the Word of God
which lives and abides forever.`"
"`All flesh is as grass,`" etc, but
"`the Word of the Lord endures forever.`" (1 Peter 1:23-25)
In the epistle to the Hebrews we have a very particular description of this divine Word.
The apostle declares that "`the Word of God is living and powerful,
and sharper than any two-edged sword,
piercing even to the division of soul and spirit, and of the joints and marrow,
and is a discerner of the thoughts and intents of the heart.
And there is there no creature that is not manifest in His sight,
but all things are naked and open to the eyes of Him with whom we have to do.`" (Heb. 4:12-13)
Here this eminent apostle ascribes the divine attribute of omniscience to the Word of God.
Now those who say the "`Word of God`" described in this text is the Scriptures
must of course ascribe this attribute (omniscience) to them; but in doing this,
they should consider whether they are not subjecting themselves to
the serious charge of _idolizing_ the Scriptures.

The apostle Paul teaches us that the holy Scriptures were given by divine inspiration
and are "`profitable for doctrine, for reproof, for correction,
for instruction in righteousness, that the man of God may be perfect,
thoroughly equipped for every good work;`" and that they
"`are able to make you wise unto salvation through faith which is in Christ Jesus.`"
(2 Tim. 3:15-17)
They bear testimony to Christ as the Savior of the world;
setting forth the doctrine which He preached when personally on earth
and describing what He did and suffered for mankind.
They also hold forth very clear declarations respecting
His spiritual appearance in the soul
in order to effect regeneration and sanctification.
But in the various dispensations of "`His grace and truth`" unto mankind,
the Lord Jesus Christ "`the High Priest of our profession,`" (Heb. 3:1)
works either directly or by outward means as He pleases.
Indeed, one of the distinguishing excellencies of the Christian dispensation is
that it leads to a communion with the Father and the Son,
which is not dependent on any external medium.
Through Christ we have "`access by one Spirit unto the Father.`" (Eph. 2:18)
While we highly esteem the benefit to be derived from the sacred record,
we should not forget that we would be abusing this precious gift if we exalt it
so as to put it in the place of Him, who is thus described:
"`In the beginning was the Word, and the Word was with God,
and the Word was God...All things were made through Him...In Him was life,
and the life was the light of men.`" (John 1:1,3,4)
Let us then, in ascribing to the Bible all the honor which
the inspired writers themselves attribute to it,
be careful not to exalt it above, nor to grant it equality with
Christ or the Holy Spirit, from whom its authority is derived.^
footnote:[Such however is the deference that is due to this authority,
that the Scriptures are to be considered as the only fit outward test
by which controversies among Christians on religious subjects are to be decided;
so that whatever doctrine is contrary to their testimony
may therefore justly be rejected as false.
Moreover, whatsoever any person pretending to have the guidance of the Spirit
may do which is contrary to the Scriptures
should be considered as the effect of delusion.
See Robert Barclay`'s [.book-title]#Apology,# Prop. 3.]

[.asterism]
'''

In publishing this concise view of the commencement and
progress of vital religion in the soul,
the writer wishes to observe
that probably it may fall into the hands of religiously
inclined persons of different denominations.
Some of these may be ready to say,
'`this doctrine does not accord with that which we have
been accustomed to hear from our ministers;
it is a doctrine which in many material points, as far as we can observe,
is seldom heard from the pulpit in the present day.`'
Should objections of this kind be excited in the minds of any persons
who in sincerity of heart are seeking that knowledge which
"`is life eternal,`" (John 17:3) the writer entreats them to consider
that this doctrine was openly declared by our Lord Jesus Christ Himself;
and that His apostles preached substantially the same truths--abundant
proof of which may be found by referring to the various texts
quoted in the preceding paragraphs.

While the reader is engaged in the investigation of this momentous subject,
he is also earnestly entreated to remember his own experience
in past seasons of serious reflection.
Have you not witnessed, at least in some degree,
the truth of the declarations of Scripture, to which, in the preceding pages,
your attention has been directed?--__Has not the light of Christ shone in your
heart?__--Has it not awakened you from a state of carnal security
and placed your transgressions in order before you,
urging you to break off from your sins by repentance and amendment of life?
You may be well assured of this truth,
that it is not the work of your soul`'s enemy thus _to detect_
and to _lay open_ his own devices: he seeks rather to deceive, to cover up,
and to darken his own ways and baits,
that their real nature and tendency may not be discovered.
It is the light of Christ Jesus our adorable Redeemer that detects and makes known
the workings of the grand deceiver.

If then you are now convinced
by the combined testimony of the Light or Spirit of Christ and of holy Scripture,
that the doctrine preached by men
(whom you have esteemed as ministers of the gospel) is
not in full accordance with that which Jesus Christ
and His apostles preached;
surely eternal happiness is at stake in your faithfully embracing the latter.
And should this course of inward conviction and renovation of heart
prove very contrary to your natural inclination,
so as to be indeed a cross difficult to be endured; yet, remember who it is that said,
"`Whoever does not bear his cross and come after Me cannot be My disciple.`" (Luke 14:27)
Be encouraged, then, to _bear this cross_ and faithfully to follow Christ
in the path of self-denial.
It is one of the greatest privileges held out to you by the Christian dispensation
that He is given to be your "`Leader,`" your spiritual guide; (Isa. 55:4)
and if, in humility of mind, you obey the instructions of His holy light revealed in your heart,
_you truly follow Christ._

As this is an important point of Christian doctrine,
the writer is inclined to repeat the assertion that only he who truly believes in
and follows the light of Christ is really a believer in and follower of Christ;
and therefore, a partaker of the benefits resulting from His sufferings and death.^
footnote:[This assertion is not invalidated by the fact
that some persons who have professed (although falsely)
a belief in the Light or Spirit of Christ
have disregarded and rejected the holy Scriptures.
As the sacred record was written under the inspiration of the Holy Spirit,
and as this divine Teacher in itself is unchangeable,
it evidently follows that its influence never can lead anyone
to despise that which it has dictated for our instruction.
Therefore they who disregard and reject the holy Scriptures do plainly show,
whatever they may profess, that their minds,
instead of being under the influence of the Light or Spirit of Christ,
are involved in gross darkness and delusion.]
On the contrary, he who in practice disregards and rejects this Light
disregards and rejects Christ; and thus deprives himself of that salvation
which those who believe in and follow Christ partake of.
These positions are supported by the texts quoted in the beginning of this chapter,
taken in connection with John 8:12, and 1 John 1:7.
Corroborating testimony appears also
in the following gracious declaration of the Almighty concerning Christ, already quoted:
__"`I will give You as a light to the Gentiles^
footnote:[The word "`Gentiles,`" in the language of Scripture,
appears to signify all mankind excepting the Jews.]
that You should be My salvation to the ends of the earth`"__ (Isa. 49:6)
They who believe in and follow this divine Light
are favored with access to the fountain of wisdom and strength.
Through faith they receive power to fulfill its requirements;
and the obedient are rewarded with peace and joy.
"`Thanks be to God for His indescribable gift!`" (2 Cor. 9:15)

May the attention of the sincere seekers after truth be turned day by day
to this inward monitor, the true spiritual guide.
It will not lead you in the least degree to disregard the holy Scriptures.
On the contrary,
it will enable you to understand them more truly in the sense in which they were written,
than the best unassisted faculties of man can do;
and to apply them most effectually for your individual instruction and comfort.
Moreover, the harmony which you will witness as you advance in your religious progress
between the law of the Spirit written on the heart
and the precepts and doctrines contained in the Bible
(as far as the latter apply to your individual states respectively)
will not fail to afford you much satisfaction and encouragement.
Then, in order that you may be kept from falling into any temptation
by which the enemy may strive to mar the Lord`'s work in your souls,
let your secret aspirations (under the influence of the Spirit of Christ)
frequently ascend unto your heavenly Father, with fervent desires
that His kingdom may come, and be set up in your hearts,
and that His holy will may be done in and by you, even in all things.
And when the Light of Christ points out what He requires of you as individuals,
both in doing that which is right in His sight, and in avoiding that which is evil,
may the language of each soul be,--"`Not my will, O Lord, but Yours be done!`"
By thus endeavoring, in all things, to follow your Redeemer by that divine aid
which will assuredly be granted to every one who seeks it in sincerity of heart,
you will find His gracious declaration, already quoted,
to be fulfilled in your experience;--"`I am the light of the world. He who follows Me
shall not walk in darkness, but have the light of life.`"

The apostle Paul made this observation respecting the
Jews:--"`When Moses is read,`" (who wrote of Christ, John 1:45)
"`a veil is upon their heart; nevertheless when it shall turn to the Lord, the veil shall be taken away.`" (2 Cor. 3:15-16)
So also it may be said now
of very many professed Christians,--that when they read the New Testament, the veil is,
in some measure, upon their heart.
For although they receive the doctrine held forth in the Scriptures
concerning the outward or personal appearance of Christ and
His sufferings and death for mankind--which doctrine the Christian faith fully
embraces--yet they are deficient with respect to that important article of the same faith
which the apostle enforces in this emphatic language:
"`Examine yourselves as to whether you are in the faith.
Test yourselves.
Do you not know yourselves,
that Jesus Christ is in you--unless indeed you are reprobates?`" (2 Cor. 13:5)
He also declares that
"`If anyone does not have the Spirit of Christ, he is not His.`" (Rom. 8:9)

We may, however, confidently entertain the same assurance
concerning the professed Christians just referred to
as the apostle expressed respecting the Jews; that is,
that when their heart "`shall turn to the Lord, the veil shall be taken away.`"
When this change takes place
_(O that it may be speedily effected!)_ they will then be prepared to receive the Light,
or Spirit of Christ, for their "`Leader.`" (Isa. 55:4)
And by submitting to His heart-purifying baptism,
and following Him in the path of regeneration and sanctification,
they will bring forth the fruit of the Spirit through its quickening,
life-giving influence.
This fruit, the apostle declares, is
"`Love, joy, peace, long-suffering, gentleness, goodness, faith, meekness, temperance.`"
(Gal. 5:22-23)
Again,
"`The fruit of the Spirit is in all goodness, righteousness, and truth.`" (Eph. 5:9)

What greater blessing can the most enlightened
philanthropist desire for the whole human race
than this,--that the fruit of the Spirit, as above described,
may be universally brought forth?
Moral evil would then be driven from the face of the earth; and
"`The kingdoms of this world [would]
become the kingdoms of our Lord, and of His Christ; [who]
shall reign forever and ever.`" (Rev. 11:15)
