[short="Chapter III -- Baptism, Worship, and the Supper"]
== Chapter III: Baptism, Worship, and Partaking of the Flesh and Blood

The qualifications required for admission into the church of Christ
do not include the observance of any of the types, ceremonies, and carnal ordinances
of the Mosaic dispensation, or of that of John the Baptist, which were fulfilled
and abrogated by the Son of God in His personal appearance and death on the cross.
But the apostle Paul plainly declares that
"`if anyone does not have the Spirit of Christ, he is not His;`" (Rom. 8:9) that is,
if any man has not accepted the Spirit of Christ for his teacher, his baptizer,
and his sanctifier; but on the contrary, in respect to these offices
has disregarded and rejected Him, this man is not Christ`'s.
Whatever may be his profession or performances as to religion,
whether he is a member of the '`Established Church,`' or a dissenter from it,
he is not a member of the spiritual body or church of which Christ is the head.
For according to the doctrine of the same apostle the baptism
by which believers are introduced into this church is the baptism of the Spirit;
(1 Cor. 12:13) consequently it is not that of water,
applied either by sprinkling or immersion.
The baptism of the Spirit is an inward work; and it should never be forgotten
that it is not the body, but the soul of man, that is the subject of it.

John the Baptist makes a very clear distinction between his baptism with water
and the baptism of Christ: "`I indeed (said he) baptize you with water unto repentance,
but He who is coming after me is mightier than I, whose shoes I am not worthy to carry;
He shall baptize you with the Holy Spirit and with fire.`" (Matt. 3:11)
And a similar and equally clear description of
the two baptisms is given by our Lord Himself (Acts 1:5).
This baptism with the Holy Spirit
is that which has been already referred to in the first chapter of this book.
It is the work of the Spirit of Christ operating in the soul of man,
principally directly, but sometimes also instrumentally by the ministry of the Gospel.
This baptizing ministry appears to have been instituted by Jesus Christ Himself,
though we do not find that He gave any commission to His disciples to baptize with _water_,
or that He so baptized any one Himself.
We read that after His resurrection He declared to them,
"`All authority has been given to Me in heaven and in earth,`"
adding "`Go therefore and teach all nations,
baptizing them in the name (the divine power and life) of the Father, and of the Son,
and of the Holy Spirit.`" (Matt. 28:18-19)

Of this baptizing ministry,
we have an instance in the account which the apostle
Peter gives of his visit to the family of Cornelius.
"`As I began to speak,`" he said,
"`the Holy Spirit fell on them as on us at the beginning;
then I remembered the word of the Lord, how He said
'`John indeed baptized with water, but you shall be baptized with the Holy Spirit.`'`"
To this the apostle added,
"`God gave them the same gift as He gave us.`" (Acts 11:15-17)

Thus the gift of the Holy Spirit appears to have accompanied the preaching of Peter
and was communicated _independently of water baptism._
However this apostle was not then fully weaned
from an attachment to this figurative ordinance;
for it appears that in this case of early Gentile conversion
he directed it to be administered to those who had previously received the Holy Spirit;
(Acts 10:47-48) although under a doubt, which the enquiry,
"`Can any man forbid water?`" seems to imply.
In process of time, however, this eminent apostle`'s views on the subject of baptism
appear to have been enlarged; for we find, that in his general epistle,
describing the baptism by which believers are now saved, he declares that
it is "`not the removal of the filth of the flesh,`"
(which is the proper effect of baptism, or washing, in water)
"`but the answer of a good conscience toward God by the resurrection of Jesus Christ.`"
(1 Peter 3:21) Now this is a description of the
effect of Christ`'s baptism with the Holy Spirit
and with fire--by which a death unto sin and a new birth unto righteousness
(through faith in that divine power by which Christ rose from the dead) are witnessed.
And thus the answer or testimony of a good conscience is produced.

The apostle Paul`'s language on this subject is also very instructive.
Having referred to the mystery which has been hid from ages and generations
but now is made manifest to the saints, which (he says) "`is Christ in you,
the hope of glory; whom we preach, warning every man
and teaching every man in all wisdom,
that we may present every man perfect in Christ Jesus;`" he then proceeds,
"`As you have therefore received Christ Jesus the Lord, so walk in Him;`"--
"`and you are complete in Him, who is the head of all principality and power;`"--
"`buried with Him in baptism,
in which you also were raised with Him, through the faith of the operation of God,
who has raised Him from the dead.`"
(Col. 1:26-28; Col. 2:6,10,12) "`Therefore we were buried with Him through baptism into death;
that just as Christ was raised from the dead by the glory of the Father,
even so we also should walk in newness of life.`" (Romans 6:4)
This is that one baptism of which the apostle speaks: (Eph. 4:4-5)
"`There is one body and one Spirit...one Lord, one faith, one baptism.`"
And describing the agent in this important work
(whether commenced through outward preaching, or not) he declares,
"`By one Spirit we were all baptized into one body,`"--or Church of Christ--
"`and have been all made to drink into one Spirit.`" (1 Cor. 12:13)

The terms "`water`" and "`fire`" are used in the New Testament
in reference to the baptism of Christ and to the new birth
which is the effect of this baptism.
It is said of Christ,
"`He will baptize you with the Holy Spirit and with fire.`" (Matt. 3:11)
Again we read,
"`Unless one is born of water and the Spirit, he cannot enter the kingdom of God.`" (John 3:5)
But these terms in the texts quoted are not to be understood literally,
but figuratively.
As the property of water is to cleanse, and that of fire to refine,
so the baptism of Christ cleanses and refines the soul which submits to it
from the stains and dross of sin.

During the apostolic age the baptism of Christ
when administered through the preaching of the Gospel
was in many instances accompanied by miraculous gifts.
Yet we have no ground to conclude now, in the absence of such gifts,
that a measure of the same baptizing influence of the
Spirit does not still accompany the ministry of those
whom He calls, qualifies, and employs in His service, and who act therein
only under His ministration and guidance, in a humble dependence on His wisdom,
life, and power.
Through the gracious continuance of divine mercy and love,
this influence is still witnessed in a greater or lesser degree when the word,
thus preached, is "`mixed with faith`" in those who hear it. (Heb. 4:2)

Some of the advocates of water baptism lay much stress on
those instances which are recorded in the New Testament
in which some of the apostles appear to have used, or to have directed the use of,
this typical ordinance.
But when it is considered that some of the apostles for a while
after the crucifixion and ascension of our Holy Redeemer
were in the practice not only of water baptism,
but also of some other typical ordinances--including circumcision--
there appears no valid reason why their practice with respect to water baptism
should be considered more obligatory on the Christian church at the present day
than their practice with respect to circumcision and some other Mosaic rites.
On a view of the whole matter there appears sufficient ground for the conclusion
that it was permitted by divine wisdom
that the typical ordinances of the preceding dispensations of Moses and of John,
although effectively abrogated by the death of Christ on the cross,
should not in the infantile state of the Church be laid aside suddenly,
but rather gradually,
as the minds of the Christian converts became capable of more clearly
comprehending the spiritual character of the Christian dispensation.

To all those whose minds are so far enlightened
as to see clearly that something more than the mere name or
outward profession of Christianity is absolutely necessary,
it is therefore earnestly recommended that,
while seeking to become in reality members of the church of Christ and sheep of His fold,
they do not endeavor to climb up through the ways which human wisdom may uphold
by a return to the use of any of the types or ordinances of former dispensations
which were fulfilled and abrogated by the coming and death of Christ,
as the Scripture declares. (Heb. 9:8-11; Col. 2:14-17)
For Christ is the door of the true sheep-fold, or church;
(John 10:9) and they who become members of it must enter in by faith in Him,
and by submission to the baptism of His Holy Spirit. (1 Cor. 12:13)

They who thus become members of the true church of Christ
are permitted to witness its blessed privileges.
They partake of that divine food which He describes as His flesh and blood.
And this food is so necessary for their preservation and growth in true religion
that He declared,
"`Unless you eat the flesh of the Son of Man and drink His blood, you have no life in you.`"
(John 6:53)

Some who heard Him speak these words thought then,
as many professed Christians appear to think in the present day,
that this declaration should be understood as relating
to the flesh and blood of His outward or material body.
Our Lord, however, graciously condescended to correct this mistake.
May every one who has adopted this
or any other outward signification of the words of Christ now under notice
very seriously reflect upon and accept the explanation which He gave
on this highly important subject.
After it had been queried,
"`How can this man give us His flesh to eat?`" this was His reply:
"`__It is the Spirit that quickens.__`"
Surely then, if it is the Spirit that quickens, or gives life, it should be concluded
that it was the partaking of the quickening, life-giving influences of His Holy Spirit
diffused in the soul--He dwelling in us and we in Him (vs 56)--
which He intended to represent by the phrases
eating His flesh and drinking His blood,
without which we have no life in us.
And, as if it were in order to place this important
point beyond the risk of mistake or doubt,
after He had said, "`__It is the Spirit that quickens,__`" He immediately added,
"`__the flesh profits nothing; the words that I speak to you
are spirit and they are life.__`" (John 6:63)

The doctrine of the apostle Paul on this very important subject
is in perfect unison with that of his divine master.
In his epistle to the Corinthians he declares that "`the Spirit gives life.`" (2 Cor. 3:6)
It also appears (from his first epistle to the same church)
that long before the incarnation of Christ
some of the Israelites partook of that spiritual food and drink
which are derived from Him; for the apostle declares that
"`they all ate the same spiritual food, and all drank the same spiritual drink;
for they drank of that spiritual Rock that followed them, and that Rock was Christ.`"
(1 Cor. 10:3-4)

If the followers of Jesus Christ could have been
permitted to eat the flesh of His material body
it is evident from His own words that it would have profited them nothing.
It was the life-giving influence of His Holy Spirit
by which alone those who believed on Him in that day were made alive
and preserved "`alive unto God.`" (Rom. 6:11)
And in the present day the same divine influence produces similar effects
in the souls of all those who,
believing in the light, life, and power of Christ, receive Him for their Teacher,
Savior, Priest, and King; believing also, if they have access to the Holy Scriptures,
all that those sacred records declare concerning the sufferings and death of Christ,
and the benefits resulting therefrom to mankind.
These partake of the true supper of the Lord; as it is written,
"`Behold, I stand at the door`" (_of the heart_)
"`and knock; if anyone hears My voice
and opens the door, I will come in to him, and will sup with him,
and he with Me.`" (Rev. 3:20)
This divine food is essentially the
same as that which our Holy Redeemer described under other figurative
terms as the bread which comes down from heaven
and gives life unto the world; (John 6:33)
and as the "`living water,`" which,
in those who drink of it, should be as a
"`well of water, springing up into everlasting life.`" (John 4:10,14)

Those who, through divine grace,
witness an advancement in the work of regeneration
should ever gratefully acknowledge
this communication of spiritual food to their souls
amidst the manifold mercies of which they partake.
Like the sap that enables the branches which abide in the vine to bring forth fruit,
so the quickening, life-giving influence of the Spirit of Christ--
who is the "`true vine`" (John 15:1)--enables those who abide as branches in Him
to bring forth the fruits of the Spirit,
which are "`in all goodness, and righteousness, and truth.`" (Eph. 5:9)
For under His holy influence
they are incited and strengthened from day to day to maintain,
even in their temporal concerns, a strict adherence to justice, truth, and equity;
doing unto others as they would that others should do unto them.
As their growth in the divine life progresses,
their words and actions become leavened by Christian purity, sincerity, humility, and love.
They exemplify, not only in their own families, but amongst all with whom they associate,
the powerful efficacy of that holy name in which they have believed,
and into which they have been baptized.

If we seriously remember the solemn declarations of our Lord Jesus Christ,
"`Unless you eat the flesh of the Son of Man and drink His blood, you have no life in you;`"
"`He who eats My flesh, and drinks My blood dwells in Me, and I in him;`" (John 6:53,56)
and if we keep in view the clear explanation
which he condescended to give of these words,
the conclusion must surely be admitted, on the highest authority,
that whatever may be our religious profession,--however
largely our minds may be furnished with the literal knowledge
of the doctrines and precepts of the Holy Scriptures,
or our memories charged with the recorded experience of good men of ancient
and modern times,--and however highly we may think of ourselves,
or be esteemed by others, on this or on any other account; yet,
__if we do not partake of the quickening influences of the Spirit of Christ,
we have no life in us;--
we do not dwell in Him, nor He in us;__ and consequently we are
in a state of spiritual darkness and death.
A conviction of the vast importance of this subject induces the writer, under
what he trusts is a degree of the constraining love of Christ,
to press it upon the close attention of those
with whom he is connected in religious profession,^
footnote:[The Society of Friends.--The writer wishes to state
that the Society is not responsible for anything contained in these pages.
{footnote-paragraph-split}
+++[+++Editors note: The fact that Samuel Rundell felt compelled to
add this note is a sad testament to the declension of the Society of Friends
during his day. Anyone familiar with the principles and writings of the
early Quakers can testify that the entirety of this publication is in perfect
agreement with them. However, by the early 1800`'s there was an alarming
departure from these first principles and a return to much of what early
Friends came out from and testified against.
Many of the most influential Quakers of Rundell`'s day
were leaning much upon the letter of the Scripture, natural learning,
and a faith in the historical appearing and death of Christ
without insisting also upon the heart`'s submission to His purifying inward baptism.
Quakers of this description had so far gained the ascendency in England
by the 1830`'s that they refused to publish this book.
At length, Samuel Rundell (with the encouragement and approbation of many
others) published it on his own, independently of the Society of Friends.+++]+++]
as well as upon Christians of every other denomination.

Having endeavored in the preceding pages to point out the means whereby the soul,
through the obedience of faith,
may attain to a capacity of partaking of this divine food,
and to show the necessity and benefits thereof,
it may be proper in the next place to make some further observations
with respect to its communication and effects.

The great Head of the church dispenses this heavenly
sustenance to the living members of His body
in their religious assemblies
when they are gathered in a state of solemn silence and reverent waiting before Him.
Sometimes this is through the instrument of an individual engaged in the ministry of the gospel,
and at other times by the immediate effusion of His Holy Spirit upon their minds.
They are also permitted to enjoy this privilege from time to time
in seasons of private retirement; and even day by day,
while engaged in their lawful occupations--if,
feeling the lack of the enlivening influence of the Spirit of Christ,
they humbly seek it.

It is preeminently for this divine nourishment--for
this bread "`that comes down from heaven,`" that our blessed Savior teaches
us to pray to our heavenly Father,--"`__Give us this day our daily bread.__`"
When favored in their public assemblies to witness the gracious promises fulfilled
that, "`They that wait upon the Lord shall renew their strength,`" (Isa. 40:31)
and that where even two or three are gathered together in His name,
__there He who is "`a quickening Spirit,`"__ (1 Cor. 15:45) __even the Lord Jesus Christ,
is in the midst of them;__ (Matt. 18:20) they can thankfully acknowledge that
although the baptizing ministry of the gospel is
a great blessing to the church of Christ,
and should be received with feelings of gratitude to the Source of all good;
yet it is a higher privilege to be fed directly by _Himself_,
the holy Head of the church and Bishop of souls,
than through the instrumentality of their fellow-members.

The solemn declaration of our Holy Redeemer to
the woman of Samaria on the subject of worship
should indeed make a deep and awful impression upon the minds of all who
profess to prostrate themselves before the Most High.
"`God is Spirit, and those who worship Him must worship Him in spirit and in truth.`"
And again He said;
"`No man comes unto the Father but by Me;`"--and "`without Me you can do nothing.`"
How needful then must it be, in order to perform this worship,
that the mind be brought into a state of entire humiliation,--bowed
down under a true sense of its great weakness,--of its many needs,
and utter unworthiness,--accompanied with a conviction
of the perfect purity of that Almighty Being
whose sacred presence is unapproachable except through our Holy Mediator,
the Lord Jesus Christ.
Perhaps it may be said
that there is no other engagement in which the religiously
exercised mind is so fully penetrated by these feelings
as in that of silent waiting upon God in assemblies for public worship.

But although Christ is always in some measure present with those who,
through the baptism of His Holy Spirit, are members of His church; yet,
according to the experience of many who are of this description,
He is frequently pleased to withhold from them for a season--
in their religious assemblies, as well as at other times--
that increased communication of His power and life
which is needful to qualify them for the performance of the solemn act of divine worship.
Yes, for a wise and gracious purpose,
He often permits them to feel how weak they are of
themselves, and how utterly insufficient by their own strength
they are to resist the efforts of their soul`'s adversary.
This adversary,
by exciting the natural propensity to be occupied with earthly things,
or by presenting to the imagination creaturely ideas relative to worship or doctrine,
often endeavors to draw off their minds from that denial of self--
that subjugation of their own will and wisdom--which are required in
order to wait patiently upon God in the exercise of faith and love.

But although He,
the good "`Shepherd and Bishop of souls,`" (1 Pet. 2:25) may
permit those humble believers in Him to be thus tried and proved,
yet He does not forsake them.
In His own time
(for which they reverently wait with fervent desire) the enlivening,
purifying influence of His Holy Spirit imparts fresh vigor to their souls.
Thus strengthened, they surmount those impediments--of whatever kind--
which had obstructed their access "`to the throne of grace;`" (Heb. 4:16)
and they are enabled to "`draw near in full assurance of faith.`" (Heb. 10:22)
The worship thus offered in religious assemblies,
whether it be accompanied with vocal ministry, prayer, or praise--
offered in obedience to the will of the great Head of the church,
directly communicated to such of its members as He may see fit to
employ in His service--or whether in obedience to the same holy will
it wholly consists in silent^
footnote:[It must not be supposed that all
who are in the practice of sitting in silence in assemblies for public worship
are benefited in the manner above described.
It is only the awakened mind--the mind in which
the work of regeneration is in some degree begun--
that is capable of truly waiting upon God in silence
under an exercise of faith and love towards Him.
Yet there is ground to believe that in numerous instances,
individuals who have previously shown little or no concern about their soul`'s salvation,
having entered a silent religious assembly
(some of them probably by mere curiosity)
have been awakened, and their minds greatly contrited by the divine power;
although not a word has been spoken.
And this visitation of the love of the Redeemer
has proved the beginning of the effectual working of His grace in their souls.]
aspirations arising from quickened souls
in a state of reverent prostration before the throne of grace,--in either case,
this worship does not fail to meet the divine acceptance.

Although many individuals in whom the work of regeneration has been begun
and who are in the practice of waiting upon God in assemblies for public worship
may not always receive such a supply of spiritual food
as the apprehension of their own need leads them to expect;
yet these should not be discouraged.
May they properly consider
that the Lord knows better than they do what is best for them.
He knows what will conduce to the progress of that great work
which he has begun in their souls.
For a wise and benign purpose
He introduces His children into a state of poverty of spirit;
the tendency of this discipline being to increase their faith,
and to establish them more firmly on Himself,
the "`sure foundation,`"--"`the Rock of Ages.`"

Therefore, you who hunger and thirst for the bread and water of life,
be not dismayed on account of the apparent smallness of the portion sometimes,
even frequently, dispensed unto you.
Should it be no more, figuratively speaking, than a crumb of this bread
or a drop of "`living water,`" yet, if received with thankfulness
it will be found sufficient for the present need,--sufficient to strengthen
you still to trust in the Lord,--still to wait upon Him in faith
and with a lively hope in His goodness and mercy.
And whenever these effects are witnessed, they should be considered as an evidence that,
through the gracious regard of your heavenly Father,
a portion of divine aid and sustenance has been dispensed unto you.
The revival of this faith and hope, when felt after much mental labor and conflict,
whether in religious assemblies or in private retirement,
how precious is it to the tribulated soul!
The Lord`'s holy name be praised for all His mercies partaken of by those
who are engaged--
although frequently under a feeling of many discouragements and infirmities--
to seek for ability to worship Him in Spirit and in truth!
