== Concluding Observations

In reviewing the subjects referred to in these pages,
the writer is inclined to say a little more on some of them,
especially on that very important one:
the benefits resulting to mankind from the sufferings and
death of our blessed Savior Jesus Christ on the cross.
This is followed by some additional remarks respecting worship and ministry,
with an exhortation to professed Christians.

The Scriptures declare that the
"`Word which was in the beginning with God, and was God, was made (or took) flesh.`"
(John 1:1-14) "`As the children have partaken of flesh and blood,
He also Himself likewise took part of the same,
that through death He might destroy him who had the power of death, that is, the devil.`"
(Heb. 2:14) "`He Himself is the propitiation for our sins, and not for ours only
but also for the sins of the whole world.`" (1 John 2:2)
He suffered death on the cross, and was buried.
On the third day He rose from the dead and ascended into heaven, where,
glorified with the Father, He is our Mediator and Intercessor with Him.

In proceeding to describe more particularly the benefits which
result to mankind from the death of Christ,
the sentiments of the writer on this subject being well
expressed in R. Barclay's
_Apology for the True Christian Divinity,_
he inserts the following selection from that work.

[quote, , "Apology, prop. 7, sec.3"]
____
We therefore consider our redemption in a two-fold
respect or state, both of which in their own nature are perfect,
though in their application to us the one cannot be
without respect to the other, as will be seen.

The first then, is the redemption performed and
accomplished by Christ for us in His crucified body without us.
The other is the redemption wrought by Christ __within__ us,
which is no less properly called and accounted a redemption than the former.
The first is that whereby man,
as he stands in the fall, is put into a capacity of salvation,
and has conveyed unto him a measure of that power,
virtue, spirit, life, and grace that was in Christ Jesus--
which, as the free gift of God, is able to overcome and root
out the evil seed with which we are naturally leavened in the fall.
The second is that whereby we experience and
know this pure and perfect redemption in ourselves, purifying,
cleansing, and redeeming us from the power of corruption,
and bringing us into unity, favor, and friendship with God.

By the first of these two, we, who were lost in Adam,
plunged into the bitter and corrupt seed, unable, of ourselves
to do any good thing, but naturally joined and united to evil,
forward and prone to all iniquity,
servants and slaves of the power and spirit of darkness, are,
notwithstanding all this, so far reconciled to God by the death of His Son,
even while enemies, that we are put into a capacity of salvation,
having the glad tidings of the Gospel of peace offered unto us,
that God is reconciled unto us in Christ,
and so calls and invites us to Himself.
It is in this respect that we understand the following scriptures:
"`He put to death the enmity in Himself;`" "`He loved us first,`"
"`Seeing us in our blood, He said unto us, Live;`"
"`He Himself bore our sins in His own body on the tree;`" and
"`Christ also suffered once for sins, the just for the unjust;`" etc.
(Eph. 2:15; 1 John 4:10; 1 Peter 2:22,24, and 3:18)

By the second, we experience this capacity brought into act,
whereby receiving and not resisting the purchase of His death
(namely, the Light, Spirit, and Grace of Christ revealed in us),
we witness and possess a real,
true and inward redemption from the power and prevalence of sin,
and so come to be truly and really redeemed, justified,
and made righteous, and to an experiential union and friendship with God.
Thus He "`gave Himself for us, that He
might redeem us from all iniquity and purify for Himself
His own special people;`"
and thus we "`know Him and the power of His resurrection,
and the fellowship of His sufferings,
being conformed to His death.`" (Tit. 2:14; Phil. 3:10)
This last follows the first in order, and is a consequence of it,
proceeding from it, as an effect proceeds from its cause.
So then, even as none can enjoy the last without the first having
been established (such being the will of God);
so also none can truly partake of the first, except as he experiences the last.
Thus to us, they are both causes of our justification.
____

It is evident from Scripture testimony
that it is absolutely required for our complete redemption
that we should individually believe in the divine light or Spirit of Christ,
and by submission to His baptism experience the work of regeneration in our souls.
Therefore, how desirable is it that among all professed Christians
(as has been already hinted) no doctrines be embraced,
nor any ordinance or institution relative to ministry and worship set up and practised,
the tendency of which is to divert their attention from this internal teacher,
or in any degree to obstruct or restrain its influence and operation in the soul.
An attentive reading of the New Testament will show
that one of the principal objects of the ministry of Jesus Christ,
and also of His apostles,
was to turn the attention of the people to this divine gift
as their teacher and guide in the way to everlasting happiness.
And surely this should be a principal object
in the view of every professed minister of Christ _in the present day_.
For the Christian religion is, in itself, the same now as it was in the apostolic age.
Yet, alas! great is the degeneracy from its original purity
among many of its professors, not only in regard to conduct and conversation,
but also respecting doctrine and worship.

True believers in Christ, after their conversion
and the remission of their past sins through His blood,
are still liable in their interaction with the world
(when the daily watching unto prayer is not fully maintained)
to contract contamination from its spirit, and also from the flesh and the devil.
When this contamination is received--however minute it may be--
it cannot escape the detection of Him who sees all things.
To whatever degree this has prevailed
it tends to obstruct the access of the soul unto God,
who is a Being of infinite purity and holiness.
Now, the great Head of the church, the High-priest and Bishop of souls,
beholds the state of every individual in religious assemblies.
And He does not fail (when He sees fit)
to dispense unto every person, according to his need,
who in the exercise of faith and love comes to Him.
He breaks the bread of life unto the pure in heart,
and in His abundant mercy He gives repentance and contrition of soul unto those who,
through unwatchfulness, have contracted any degree of defilement,
"`sprinkling their hearts from an evil conscience.`" (Heb. 10:22)

Thus the gracious declaration of our Lord is verified,
"`Where two or three are gathered together in My name,`"
(and consequently also when a larger number is so gathered)
"`I am there in the midst of them.`" (Matt. 18:20)
For these words of our holy Redeemer are not unmeaning sounds;
they are definite and most certain truths.
What a blessed privilege it is then
that a religious assembly _may_ witness the life-giving
presence of Christ revealed in and among them!
But it should ever be borne in mind that this high privilege is held out to those,
and to those only, who are gathered in His name.
His name, as has already been observed,
signifies or has reference to His divine attributes, namely His power, life, light, etc.

In order that we may participate in this high privilege
the command of our Holy Redeemer to His disciples
should not be forgotten:
__"`What I say unto you I say unto all, watch!`"__ and again,
__"`Watch and pray, that you do not enter into temptation.`"__ (Mark 13:37; Matt. 26:41)
It is indeed a duty very needful to be observed in the
course of our daily conduct and conversation among men,
but on no occasion is the practice of watching more necessary
than in assemblies for public worship.
For there is reason to believe that the enemy of all good strives
by every means in his power
to prevent the worshipping of Almighty God in spirit and in truth;
and the human mind by its own strength is entirely incompetent to withstand his efforts.

"`The hour is coming, and now is,
when the true worshippers will worship the Father in spirit and in truth;
for the Father is seeking such worship Him.`" (John 4:23)
This declaration of Jesus Christ on this important subject
affords sufficient ground for the conclusion
that it is consistent with the will of our heavenly Father that this
pure spiritual worship should everywhere prevail.
Therefore, when assembled for the purpose of divine worship, how indispensable
to being preserved from opposing the divine will in this matter
is a uniform, implicit adherence to the injunction of our Lord
that "`all,`" of every denomination in His militant church, should "`__watch.__`"
This diligent watching is necessary in order that
the supplications of their souls may ascend unto Him
under the influence of His Holy Spirit,
and that they may not enter into any of the temptations of the enemy--
including the temptation to preach, or vocally to pray or sing
before the quickening influence of the Spirit of Christ
is felt distinctly to lead into any one of these acts.

The duty of watching may be understood to also include the duty of waiting upon God;
and if this duty is patiently persevered in
there is a gracious assurance that the result will be a renewal of strength. (Isa. 40:31)
Thus invigorated, true believers--
through the lovingkindness and strength of the Lord--
will surmount the temptations of their souls' adversary
and will be enabled to worship the Father of spirits in spirit and in truth.
This worship in solemn and reverential silence may then be followed,
as often as the great Head of the church shall be pleased to direct,
by vocal ministry, prayer, and praise.
And this direction, communicated by the immediate influence of His Holy Spirit
when and as He sees fit to give it in religious assemblies,
will be clearly understood by those individuals
(if duly watchful and attentive) whom He may be
pleased to entrust with a gift of the ministry.
He will also furnish them with the needful supplies of that
"`wisdom which is from above`" for the edification of His church.
As their dependence is placed _on this wisdom and not on their own,_
then only will the apostolic direction be thoroughly complied with:
"`If anyone speaks,
let him speak as the oracles of God; if anyone ministers,
let him do it as with the ability which God supplies,
that in all things God may be glorified through Jesus Christ.`" (1 Pet. 4:11)

In divine worship,
agreeable to the various texts of Holy Scripture bearing on this subject,
the life-giving influence of the Spirit of Christ
should be regarded as the only true spring to action.
The will and wisdom of man should not be allowed to predominate, or take the lead,
but should be kept in entire subserviency.
The general tenor of those declarations and promises which the Scriptures hold forth
relative to Christ and His Holy Spirit
describes Him as being given to mankind to be their Lord--their
Leader--their Guide--their Shepherd--their High Priest, etc.
(John 13:13; Isa. 55:4; John 10:14, and 16:13; Heb. 2:17)
Now these phrases convey the idea of _precedence, of direction, of going before_--
but not of following.
Accordingly we find that when our Lord described
Himself as "`the good Shepherd,`" He said,
"`When he puts forth His own sheep, he goes before them, and the sheep follow Him;
for they know His voice.`" (John 10:4)
"`The good Shepherd`" then "`puts forth His own sheep`"
_in all their religious services_--in public assemblies and on other occasions.

If therefore it is admitted that the worship which is in spirit and in truth
is performed only under the quickening influence
and guidance of the Spirit of Christ--
it behooves all professors of Christianity
very seriously to consider whether they are performing this worship
when in their public assemblies they begin their religious services according to a
previously prescribed form, or when their ministers depend on their own wisdom
for a supply of matter for their sermons and prayers.
If their worship commences in this manner
and is performed in this way,--or
for those professed Christians who do not use any prescribed forms of worship,
if any of their ministers are not careful to reverently wait for that
"`ability which God gives,`" (1 Peter 4:11)
and if they presume to preach or to pray in their assemblies
without this essential qualification--
it should be a subject of grave consideration
whether in all these cases they are proceeding
without the only sure Guide and Leader
and substituting another leader, human wisdom, in its stead.
For indeed we have no ground from the testimony of holy Scripture to expect
that the Spirit of Christ _will follow us_ with its life-giving influence
when we put ourselves under the direction of our own will and wisdom
by beginning to preach, or to pray, or to sing in our religious assemblies
before the quickening influence of the Spirit of Christ is felt to
put forth and lead in the performance of any of these acts.

Far be it, however, from the writer
to assign any limits to the love and mercy of our Lord Jesus Christ.
He fully believes that in very many instances,
where uprightness and sincerity of heart are found,
our Holy Redeemer graciously condescends to render religious services,
which are in some degree of the character now described,
effectual to awaken the unconverted,
to convince them of the danger of living in forgetfulness of God,
and to excite in their hearts a lively feeling of their need of a Savior.
However, it is of great importance that this gracious condescension of infinite goodness
may not be held up as an argument to obstruct their reception of and obedience to
such further manifestations of divine light
as may enable them more clearly to discriminate
between that worship which is in spirit and in truth,
and those performances to which the appellation
of '`will-worship`' is in any degree applicable.

When we consider that the well-being in this life,
and eternal happiness hereafter of every individual
depends on their becoming not merely a nominal, but a real Christian--
the subject then appears clearly to be of the greatest importance.
For, as said our blessed Savior,
"`What will it profit a man if he gains the whole world, and loses his own soul?`"
Let then every professed Christian be stimulated
not to place his dependence on being a member of any religious community,
or on being in the practice of joining in any external form of worship
or ceremonial observance.
Rather let him,
with an anxiety in some degree equal to the importance of the subject,
seek after an experiential knowledge of the power of God inwardly revealed;
that by submission to its humbling operation
"`every mountain and hill (of self-exaltation) may be brought low;`" (Luke 3:5)
and in this way every obstacle to his coming unto Christ,
and partaking of the salvation which is by Him, may be effectually removed.

With this important object in view,
let us apply to ourselves a portion of the doctrine referred to in the preceding pages.
God, in His infinite love to mankind, has declared respecting Christ:
"`I will give You as a light to the Gentiles,
that You should be My salvation to the ends of the earth.`" (Isa. 49:6)
And our Holy Redeemer, referring to this divine gift
and describing the cause of the condemnation of those who perish,
said "`This is the condemnation, that light is come into the world,
and men loved darkness rather than light, because their deeds were evil.`"
Therefore, that we may not bring on ourselves this condemnation
by _our_ not loving but disregarding and rejecting Christ
in His manifestation as the Light,
let a heart-searching examination take place individually
by a conscientious application to ourselves of the following questions.

Do you believe in Christ,
in reference to His spiritual appearance in your own soul? (2 Cor. 13:5)
Have you, in the metaphorical language of Scripture,
opened the door of your heart unto Him, when,
by the secret convictions of His holy Light or Spirit,
He has knocked there for admission? (Rev. 3:20)
Have you in this way received Christ to be your leader, (Isaiah 55:4)
your baptizer, (Matt. 3:11)
your high-priest and your king? (Heb. 2:17; Isaiah 33:22)
Has it become your daily concern to obey Him in all things,
avoiding in every part of your conduct and conversation
that which the light manifests to be evil, (John 3:20-21)
denying yourself and taking up the cross
in respect to every pursuit and gratification which this divine Monitor does not allow,
however earnestly pleaded for by your natural inclination and desires? (Luke 9:23)
And finally, do you witness,
through submission to the baptizing operation of His Holy Spirit,
the work of regeneration begun, and gradually progressing in your soul? (John 3:3)

To promote this great work of reformation among
professing Christians of every denomination,
is the object which the writer has in view.
He fervently desires that the awakening visitations of divine love and mercy
may be extensively embraced,--that great may be the number of those
who, feeling the burden of sin and their need of a Savior,
and under the conviction that the form of godliness without the power cannot save them,
will be prepared to accept the gracious invitation,
"`Come to Me, all you who labour and are heavy laden, and I will give you rest;
take My yoke upon you, and learn of Me, for I am meek and lowly in heart;
and you will find rest for your souls.`"
As a general concern prevails to come in this manner unto Christ--
to submit to His yoke,
and to learn of and to be baptized by Him--
the fruit of His Holy Spirit will be abundantly produced.
Then genuine Christianity will again shine forth in her ancient beauty;
the name of Almighty God will be glorified by the consistent
conduct and conversation of professed Christians;
and in their religious assemblies,
the will and wisdom of man being no longer allowed to predominate,
but rather being kept in due subserviency, the eternal light, life,
power and wisdom of our God will be exalted in dominion over all.

[.small-break]
'''

__'`Even so, Holy Father, Your kingdom come, Your will be done on earth,
as it is done in heaven.`'__
