== Introduction

When we look around us
and observe how many conflicting creeds and systems of
Christianity are actively promoted in the present day,
our reflections on the subject should lead us to
properly appreciate the privileges with which,
through divine love and mercy, we are favored;
for the Light of Christ has been given to illuminate our minds,
and the holy Scriptures have been placed within our reach,
to which we can refer for instruction.

In that sacred record the doctrine preached by our Lord and Savior Jesus Christ
on the subject of the redemption and salvation of man is clearly exhibited.
As there is no other subject of equal interest and importance,
these few pages were written to point out from this high authority the way by which
all mankind may come to the knowledge of the truth and be saved.
May they prove the means, under the divine blessing,
not only of convincing the merely nominal Christian of the imminent danger he is in;
but also of encouraging the weak yet sincere believer
to hold fast his "`grain`" of living faith; (Matt. 17:20) so that,
amid all the conflicts with which he may be proved,
his confidence may be steadily fixed on Him who is the
"`wisdom of God, and the power of God.`" (1 Cor. 1:24)
By submission to His command, "`Take My yoke upon you, and learn of me,`"
and by the resulting fulfillment of His gracious promise
"`You shall find rest unto your souls,`" (Matt. 11:29) the sincere
believer will be enabled eventually to adopt the ancient language,
"`The Lord is my light, and my salvation;
whom shall I fear? The Lord is the strength of my life;
of whom shall I be afraid?`" (Ps. 27:1)
